import "server-only";

import { getDb } from "@/db/client";
import { SITE_URL } from "@/lib/site";

export type AlertSource = "GSC" | "GA4" | "Auditoría" | "CWV" | "Indexación" | "Integraciones";
export type AlertSeverity = "critical" | "high" | "medium" | "low";
export type AlertStatus = "new" | "reviewed" | "resolved";
export type Alert = { id: number; fingerprint: string; source: AlertSource; rule: string; entity: string | null; severity: AlertSeverity; title: string; message: string; metric: string | null; currentValue: number | null; previousValue: number | null; variation: number | null; detectedAt: string; relatedUrl: string | null; recommendation: string; status: AlertStatus };
export type AlertEvaluation = { alerts: Alert[]; evaluatedAt: string; evaluatedSources: AlertSource[]; pendingSources: string[]; persistence: "database" | "session" };

type Candidate = Omit<Alert, "id" | "detectedAt" | "status">;
type Metric = { metric: string; title: string; threshold: number; current: number; previous: number; recommendation: string; severity?: AlertSeverity };
type AuditIssueSnapshot = { id: string; severity: string; issue: string; evidence: string; recommendation: string };
type AuditedPageSnapshot = { url: string; title?: string | null; metaDescription?: string | null };
type VitalSnapshot = { status?: string; metrics?: Record<string, unknown> };
type IndexationRowSnapshot = { url?: string; status?: string; userCanonical?: string | null; googleCanonical?: string | null };
type Snapshot = { crawler?: { issues?: AuditIssueSnapshot[]; audited?: AuditedPageSnapshot[] }; devices?: Record<string, Record<string, VitalSnapshot>>; indexing?: { notIndexed?: unknown }; inspection?: { rows?: IndexationRowSnapshot[] }; sitemaps?: { rows?: Array<{ path?: string; warnings?: string[]; errors?: string[] }> } };

const pct = (current: number, previous: number) => previous === 0 ? null : ((current - previous) / previous) * 100;
const finite = (value: unknown): value is number => typeof value === "number" && Number.isFinite(value);
const n = (value: unknown) => Number(value ?? 0);
const candidate = (source: AlertSource, rule: string, item: Omit<Candidate, "source" | "rule" | "fingerprint">): Candidate => ({ ...item, source, rule, fingerprint: `${source}:${rule}:${item.entity ?? "site"}:14d` });

function metricAlerts(source: AlertSource, rule: string, metric: Metric, direction: "down" | "up" = "down", entity: string | null = null): Candidate[] {
  const variation = pct(metric.current, metric.previous);
  if (variation === null || (direction === "down" ? variation >= -metric.threshold : metric.current - metric.previous <= metric.threshold)) return [];
  const amount = Math.abs(variation).toFixed(1);
  return [candidate(source, rule, { entity, severity: metric.severity ?? (Math.abs(variation) >= 35 ? "critical" : "high"), title: metric.title, message: `${metric.metric}: ${metric.current.toLocaleString("es-ES")} frente a ${metric.previous.toLocaleString("es-ES")} (${variation > 0 ? "+" : ""}${amount}%).`, metric: metric.metric, currentValue: metric.current, previousValue: metric.previous, variation, relatedUrl: entity, recommendation: metric.recommendation })];
}

async function performanceCandidates(): Promise<{ candidates: Candidate[]; sources: AlertSource[]; pending: string[] }> {
  const db = getDb();
  const candidates: Candidate[] = [];
  const sources: AlertSource[] = [];
  const pending: string[] = [];
  const gsc = await db.query<{ rows: number; currentClicks: number; previousClicks: number; currentImpressions: number; previousImpressions: number; currentCtr: number; previousCtr: number; currentPosition: number; previousPosition: number }>(`WITH bounds AS (SELECT MAX(day) AS max_day FROM gsc_performance_daily WHERE site_url = $1), grouped AS (SELECT COUNT(*) FILTER (WHERE day > max_day - 14) AS current_rows, COUNT(*) FILTER (WHERE day > max_day - 28 AND day <= max_day - 14) AS previous_rows, SUM(clicks) FILTER (WHERE day > max_day - 14) AS current_clicks, SUM(clicks) FILTER (WHERE day > max_day - 28 AND day <= max_day - 14) AS previous_clicks, SUM(impressions) FILTER (WHERE day > max_day - 14) AS current_impressions, SUM(impressions) FILTER (WHERE day > max_day - 28 AND day <= max_day - 14) AS previous_impressions, CASE WHEN SUM(impressions) FILTER (WHERE day > max_day - 14) > 0 THEN SUM(clicks) FILTER (WHERE day > max_day - 14) / SUM(impressions) FILTER (WHERE day > max_day - 14) * 100 END AS current_ctr, CASE WHEN SUM(impressions) FILTER (WHERE day > max_day - 28 AND day <= max_day - 14) > 0 THEN SUM(clicks) FILTER (WHERE day > max_day - 28 AND day <= max_day - 14) / SUM(impressions) FILTER (WHERE day > max_day - 28 AND day <= max_day - 14) * 100 END AS previous_ctr, CASE WHEN SUM(impressions) FILTER (WHERE day > max_day - 14) > 0 THEN SUM(position * impressions) FILTER (WHERE day > max_day - 14) / SUM(impressions) FILTER (WHERE day > max_day - 14) END AS current_position, CASE WHEN SUM(impressions) FILTER (WHERE day > max_day - 28 AND day <= max_day - 14) > 0 THEN SUM(position * impressions) FILTER (WHERE day > max_day - 28 AND day <= max_day - 14) / SUM(impressions) FILTER (WHERE day > max_day - 28 AND day <= max_day - 14) END AS previous_position FROM gsc_performance_daily, bounds WHERE site_url = $1 AND day > max_day - 28) SELECT (current_rows + previous_rows)::int AS rows, COALESCE(current_clicks, 0)::float AS "currentClicks", COALESCE(previous_clicks, 0)::float AS "previousClicks", COALESCE(current_impressions, 0)::float AS "currentImpressions", COALESCE(previous_impressions, 0)::float AS "previousImpressions", current_ctr::float AS "currentCtr", previous_ctr::float AS "previousCtr", current_position::float AS "currentPosition", previous_position::float AS "previousPosition" FROM grouped`, [SITE_URL]);
  const g = gsc.rows[0];
  if (!g || g.rows < 14) pending.push("GSC: faltan dos períodos comparables"); else { sources.push("GSC"); candidates.push(...metricAlerts("GSC", "clicks_drop", { metric: "Clicks", title: "Caída de clicks orgánicos", threshold: 20, current: g.currentClicks, previous: g.previousClicks, recommendation: "Revisar consultas y páginas que perdieron demanda o posiciones." }), ...metricAlerts("GSC", "impressions_drop", { metric: "Impressions", title: "Caída de impresiones", threshold: 20, current: g.currentImpressions, previous: g.previousImpressions, recommendation: "Revisar cobertura, indexación y visibilidad de las páginas afectadas." }), ...metricAlerts("GSC", "ctr_drop", { metric: "CTR", title: "Caída de CTR", threshold: 15, current: g.currentCtr, previous: g.previousCtr, recommendation: "Revisar titles y snippets de las consultas con más impresiones." }), ...metricAlerts("GSC", "position_worse", { metric: "Posición media", title: "Empeoramiento de posición media", threshold: 2, current: g.currentPosition, previous: g.previousPosition, recommendation: "Comparar las consultas y páginas prioritarias del período anterior." }, "up").map((item) => ({ ...item, variation: g.currentPosition - g.previousPosition }))); }

  const ga4 = await db.query<{ rows: number; currentUsers: number; previousUsers: number; currentSessions: number; previousSessions: number; currentConversions: number; previousConversions: number; currentEngagement: number; previousEngagement: number }>(`WITH bounds AS (SELECT MAX(day) AS max_day FROM ga4_daily WHERE site_url = $1), grouped AS (SELECT COUNT(*) FILTER (WHERE day > max_day - 14) AS current_rows, COUNT(*) FILTER (WHERE day > max_day - 28 AND day <= max_day - 14) AS previous_rows, SUM(users) FILTER (WHERE day > max_day - 14) AS current_users, SUM(users) FILTER (WHERE day > max_day - 28 AND day <= max_day - 14) AS previous_users, SUM(sessions) FILTER (WHERE day > max_day - 14) AS current_sessions, SUM(sessions) FILTER (WHERE day > max_day - 28 AND day <= max_day - 14) AS previous_sessions, SUM(conversions) FILTER (WHERE day > max_day - 14) AS current_conversions, SUM(conversions) FILTER (WHERE day > max_day - 28 AND day <= max_day - 14) AS previous_conversions, CASE WHEN SUM(sessions) FILTER (WHERE day > max_day - 14) > 0 THEN SUM(engaged_sessions) FILTER (WHERE day > max_day - 14) / SUM(sessions) FILTER (WHERE day > max_day - 14) * 100 END AS current_engagement, CASE WHEN SUM(sessions) FILTER (WHERE day > max_day - 28 AND day <= max_day - 14) > 0 THEN SUM(engaged_sessions) FILTER (WHERE day > max_day - 28 AND day <= max_day - 14) / SUM(sessions) FILTER (WHERE day > max_day - 28 AND day <= max_day - 14) * 100 END AS previous_engagement FROM ga4_daily, bounds WHERE site_url = $1 AND day > max_day - 28 AND channel = 'Organic Search') SELECT (current_rows + previous_rows)::int AS rows, COALESCE(current_users, 0)::float AS "currentUsers", COALESCE(previous_users, 0)::float AS "previousUsers", COALESCE(current_sessions, 0)::float AS "currentSessions", COALESCE(previous_sessions, 0)::float AS "previousSessions", COALESCE(current_conversions, 0)::float AS "currentConversions", COALESCE(previous_conversions, 0)::float AS "previousConversions", current_engagement::float AS "currentEngagement", previous_engagement::float AS "previousEngagement" FROM grouped`, [SITE_URL]);
  const a = ga4.rows[0];
  if (!a || a.rows < 14) pending.push("GA4: faltan dos períodos comparables"); else { sources.push("GA4"); candidates.push(...metricAlerts("GA4", "sessions_drop", { metric: "Sesiones orgánicas", title: "Caída de sesiones orgánicas", threshold: 20, current: a.currentSessions, previous: a.previousSessions, recommendation: "Revisar adquisición orgánica y las landing pages con mayor pérdida." }), ...metricAlerts("GA4", "users_drop", { metric: "Usuarios orgánicos", title: "Caída de usuarios orgánicos", threshold: 20, current: a.currentUsers, previous: a.previousUsers, recommendation: "Validar cobertura de tráfico orgánico y cambios de etiquetado." }), ...metricAlerts("GA4", "conversions_drop", { metric: "Conversiones / key events", title: "Caída de conversiones orgánicas", threshold: 15, current: a.currentConversions, previous: a.previousConversions, recommendation: "Revisar key events, páginas de entrada y calidad del tráfico." }), ...metricAlerts("GA4", "engagement_drop", { metric: "Engagement rate", title: "Caída significativa de engagement", threshold: 15, current: a.currentEngagement, previous: a.previousEngagement, recommendation: "Revisar experiencia y contenido de las landing pages orgánicas." })); }
  return { candidates, sources, pending };
}

function snapshotCandidates(latest: Snapshot | undefined, previous: Snapshot | undefined): Candidate[] {
  const result: Candidate[] = []; const currentIssues = latest?.crawler?.issues ?? []; const previousIds = new Set((previous?.crawler?.issues ?? []).map((item) => item.id));
  for (const issue of currentIssues.filter((item) => (item.severity === "Alta" || item.severity === "Crítica") && !previousIds.has(item.id))) result.push(candidate("Auditoría", "new_high_issue", { entity: issue.id, severity: issue.severity === "Crítica" ? "critical" : "high", title: `Nuevo issue ${issue.severity.toLowerCase()}`, message: `${issue.issue}: ${issue.evidence}`, metric: "Issue", currentValue: 1, previousValue: 0, variation: null, relatedUrl: issue.evidence.match(/https?:\/\/\S+/)?.[0] ?? null, recommendation: issue.recommendation }));
  const currentPages = latest?.crawler?.audited ?? []; for (const page of currentPages) { for (const [key, label] of [["title", "Title ausente"], ["metaDescription", "Meta description ausente"]] as const) if (!page[key] && (previous?.crawler?.audited ?? []).some((old) => old.url === page.url && old[key])) result.push(candidate("Auditoría", key, { entity: page.url, severity: "medium", title: label, message: `${label} detectado en ${page.url}.`, metric: label, currentValue: 1, previousValue: 0, variation: null, relatedUrl: page.url, recommendation: "Completar el elemento en la plantilla o página correspondiente." })); }
  for (const device of ["mobile", "desktop"]) for (const kind of ["psi", "crux"]) { const current = latest?.devices?.[device]?.[kind]; const old = previous?.devices?.[device]?.[kind]; if (!current || current.status !== "live") continue; for (const [metric, value] of Object.entries(current.metrics ?? {})) { const previousValue = old?.metrics?.[metric]; if (!finite(value) || !finite(previousValue)) continue; const bad = metric === "lcp" ? value > 4000 : metric === "inp" ? value > 500 : metric === "cls" ? value > 0.25 : false; const degraded = metric === "cls" ? value > previousValue + 0.05 : value > previousValue * 1.15; if (bad || degraded) result.push(candidate("CWV", `${kind}_${metric}`, { entity: `${device}:${kind}`, severity: bad ? "high" : "medium", title: `${metric.toUpperCase()} necesita atención`, message: `${metric.toUpperCase()} ${device}: ${value} (anterior ${previousValue}).`, metric: metric.toUpperCase(), currentValue: value, previousValue, variation: pct(value, previousValue), relatedUrl: SITE_URL, recommendation: bad ? "Priorizar la optimización de esta métrica según el diagnóstico de PageSpeed/CrUX." : "Investigar la degradación frente al snapshot anterior." })); } }
  return result;
}

function indexationCandidates(latest: Snapshot, previous: Snapshot): Candidate[] {
  const oldRows = new Map((previous.inspection?.rows ?? []).map((row) => [row.url, row])); const result: Candidate[] = [];
  for (const row of latest.inspection?.rows ?? []) {
    if (!row.url) continue;
    const old = oldRows.get(row.url);
    if (old && old.status !== "not_indexed" && row.status === "not_indexed") result.push(candidate("Indexación", "url_not_indexed", { entity: row.url, severity: "high", title: "Una URL dejó de estar indexada", message: `${row.url} pasó a estado no indexado.`, metric: "Estado de indexación", currentValue: 0, previousValue: 1, variation: -100, relatedUrl: row.url, recommendation: "Inspeccionar la URL en Search Console y revisar cobertura, robots y canonical." }));
    if (row.googleCanonical && row.userCanonical && row.googleCanonical !== row.userCanonical) result.push(candidate("Indexación", "canonical_mismatch", { entity: row.url, severity: "medium", title: "Canonical de Google distinto al declarado", message: `Declarado: ${row.userCanonical}. Google: ${row.googleCanonical}.`, metric: "Canonical", currentValue: 1, previousValue: 0, variation: null, relatedUrl: row.url, recommendation: "Revisar señales canónicas, contenido duplicado y enlaces internos." }));
  }
  for (const sitemap of latest.sitemaps?.rows ?? []) if ((sitemap.warnings?.length ?? 0) + (sitemap.errors?.length ?? 0) > 0) result.push(candidate("Indexación", "sitemap_issue", { entity: sitemap.path ?? "sitemap", severity: sitemap.errors?.length ? "high" : "medium", title: "Sitemap con warnings o errores", message: `${sitemap.path ?? "Sitemap"}: ${sitemap.warnings?.length ?? 0} warnings y ${sitemap.errors?.length ?? 0} errores.`, metric: "Sitemap issues", currentValue: (sitemap.warnings?.length ?? 0) + (sitemap.errors?.length ?? 0), previousValue: 0, variation: null, relatedUrl: sitemap.path ?? null, recommendation: "Revisar las URLs y respuestas que reporta el sitemap en Search Console." }));
  return result;
}

async function persist(candidates: Candidate[]): Promise<Alert[]> { const db = getDb(); for (const item of candidates) await db.query(`INSERT INTO alerts (site_url, fingerprint, source, rule, entity, severity, title, message, metric, current_value, previous_value, variation, detected_at, related_url, recommendation, status) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,NOW(),$13,$14,'new') ON CONFLICT (site_url, fingerprint) DO UPDATE SET source=EXCLUDED.source, rule=EXCLUDED.rule, severity=EXCLUDED.severity, title=EXCLUDED.title, message=EXCLUDED.message, metric=EXCLUDED.metric, current_value=EXCLUDED.current_value, previous_value=EXCLUDED.previous_value, variation=EXCLUDED.variation, detected_at=NOW(), related_url=EXCLUDED.related_url, recommendation=EXCLUDED.recommendation, status=CASE WHEN alerts.status = 'resolved' THEN 'new' ELSE alerts.status END`, [SITE_URL, item.fingerprint, item.source, item.rule, item.entity, item.severity, item.title, item.message, item.metric, item.currentValue, item.previousValue, item.variation, item.relatedUrl, item.recommendation]);
  const rows = await db.query<Alert>(`SELECT id, fingerprint, source, rule, entity, severity, title, message, metric, current_value AS "currentValue", previous_value AS "previousValue", variation, detected_at AS "detectedAt", related_url AS "relatedUrl", recommendation, status FROM alerts WHERE site_url = $1 ORDER BY CASE severity WHEN 'critical' THEN 1 WHEN 'high' THEN 2 WHEN 'medium' THEN 3 ELSE 4 END, detected_at DESC`, [SITE_URL]); return rows.rows; }

async function ensureAlertsTable() { const db = getDb(); await db.query(`CREATE TABLE IF NOT EXISTS alerts (id BIGSERIAL PRIMARY KEY, site_url TEXT NOT NULL, fingerprint TEXT NOT NULL, source TEXT NOT NULL, rule TEXT NOT NULL, entity TEXT, severity TEXT NOT NULL, title TEXT NOT NULL, message TEXT NOT NULL, metric TEXT, current_value NUMERIC, previous_value NUMERIC, variation NUMERIC, detected_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), related_url TEXT, recommendation TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'new', UNIQUE (site_url, fingerprint))`); await db.query(`CREATE INDEX IF NOT EXISTS alerts_site_status_idx ON alerts (site_url, status, detected_at DESC)`); }

export async function evaluateAlerts(): Promise<AlertEvaluation> { const at = new Date().toISOString(); if (!process.env.DATABASE_URL && !process.env.POSTGRES_URL && !process.env.POSTGRES_URL_NON_POOLING) return { alerts: [], evaluatedAt: at, evaluatedSources: [], pendingSources: ["Base de datos no configurada"], persistence: "session" }; try { await ensureAlertsTable(); const db = getDb(); const [performance, audit, history, sync] = await Promise.all([performanceCandidates(), db.query<{ snapshot: Snapshot }>(`SELECT snapshot FROM audit_runs WHERE site_url=$1 ORDER BY completed_at DESC LIMIT 2`, [SITE_URL]), db.query<{ snapshot: Snapshot }>(`SELECT snapshot FROM indexation_runs WHERE site_url=$1 ORDER BY completed_at DESC LIMIT 2`, [SITE_URL]), db.query<{ source: string; status: string; lastSuccessAt: string | null }>(`SELECT source,status,last_success_at AS "lastSuccessAt" FROM synchronization WHERE source IN ('search-console','analytics')`, [])]); const candidates = [...performance.candidates, ...snapshotCandidates(audit.rows[0]?.snapshot, audit.rows[1]?.snapshot)]; const pending = [...performance.pending]; const syncNames = new Set(sync.rows.map((row) => row.source)); for (const source of ["search-console", "analytics"]) if (!syncNames.has(source)) pending.push(`${source}: sin snapshot reciente o con error`); for (const row of sync.rows) if (row.status === "error" || !row.lastSuccessAt || Date.now() - new Date(row.lastSuccessAt).getTime() > 7 * 86400000) pending.push(`${row.source}: sin snapshot reciente o con error`); if (history.rows.length < 2) pending.push("Indexación: falta snapshot anterior para comparar"); else { const current = history.rows[0].snapshot; const old = history.rows[1].snapshot; const currentNot = n(current?.indexing?.notIndexed); const oldNot = n(old?.indexing?.notIndexed); if (currentNot > oldNot) candidates.push(candidate("Indexación", "not_indexed_increase", { entity: "site", severity: "high", title: "Aumentan las URLs no indexadas", message: `${currentNot} URLs no indexadas frente a ${oldNot}.`, metric: "URLs no indexadas", currentValue: currentNot, previousValue: oldNot, variation: pct(currentNot, oldNot), relatedUrl: "/indexacion", recommendation: "Revisar cobertura e inspeccionar las URLs nuevas no indexadas." })); }
  if (history.rows.length >= 2) candidates.push(...indexationCandidates(history.rows[0].snapshot, history.rows[1].snapshot)); const alerts = await persist(candidates); return { alerts, evaluatedAt: at, evaluatedSources: [...performance.sources, ...(audit.rows.length ? ["Auditoría" as AlertSource] : []), ...(history.rows.length ? ["Indexación" as AlertSource] : [])], pendingSources: pending, persistence: "database" };
  } catch (error) { return { alerts: [], evaluatedAt: at, evaluatedSources: [], pendingSources: [error instanceof Error ? error.message : "No se pudo evaluar la base de datos"], persistence: "session" }; } }

export async function updateAlertStatus(id: number, status: AlertStatus) { if (!Number.isInteger(id) || !["new", "reviewed", "resolved"].includes(status)) throw new Error("Solicitud inválida."); const result = await getDb().query(`UPDATE alerts SET status = $1 WHERE id = $2 AND site_url = $3`, [status, id, SITE_URL]); if (!result.rowCount) throw new Error("Alerta no encontrada."); return evaluateAlerts(); }
