"use client";

import { useParams } from "next/navigation";
import { DashboardShell } from "@/components/dashboard-shell";
import { Card, EmptyState, FilterBar, SectionHeading } from "@/components/ui";
import { AnalyticsLive, KeywordsLive, SearchConsoleLive } from "@/components/integration-panels";
import { AuditPanel } from "@/components/audit-panel";
import { IndexationPanel } from "@/components/indexation-panel";

const titles: Record<string, [string, string, string]> = { "search-console": ["Search Console", "Rendimiento de búsqueda orgánica", "Consulta datos reales de Search Console."], analytics: ["Analytics", "El tráfico que mueve el negocio", "Consulta datos reales de GA4."], indexacion: ["Indexación", "Cobertura real del sitio", "Sitemap XML, URL Inspection y crawler, con fuentes separadas."], "auditoria-tecnica": ["Auditoría técnica", "La salud detrás del ranking", "Resultados reales de crawler, PageSpeed y CrUX."], keywords: ["Keywords", "El lenguaje de tu audiencia", "Las keywords se mostrarán cuando exista una fuente conectada."], contenido: ["Contenido", "Contenido que encuentra a las personas", "El contenido se mostrará cuando exista un backend conectado."], alertas: ["Alertas", "Señales para actuar a tiempo", "Las alertas se mostrarán cuando exista una fuente conectada."], configuracion: ["Configuración", "Fuentes de datos", "Estado de las conexiones disponibles."] };
export default function SectionPage() { const { section } = useParams<{ section: string }>(); const [label, title, description] = titles[section] ?? titles.configuracion; return <DashboardShell><SectionHeading eyebrow={label} title={title} description={description} />{section === "search-console" ? <><FilterBar /><SearchConsoleLive /></> : section === "analytics" ? <><FilterBar /><AnalyticsLive /></> : section === "keywords" ? <><FilterBar /><KeywordsLive /></> : section === "auditoria-tecnica" ? <AuditPanel /> : section === "indexacion" ? <IndexationPanel /> : section === "configuracion" ? <Configuration /> : <NotConnected section={label} />}</DashboardShell>; }
function NotConnected({ section }: { section: string }) { return <Card><EmptyState title="No data available" detail={`${section}: fuente no conectada. Conecta el backend o la API correspondiente para mostrar datos reales.`} /></Card>; }
function Configuration() { return <div className="settings-grid"><Card><EmptyState title="Search Console · Unavailable" detail="Falta GSC_SITE_URL y credenciales de Google." /></Card><Card><EmptyState title="GA4 · Unavailable" detail="Falta GA4_PROPERTY_ID y credenciales de Google." /></Card><Card><EmptyState title="Auditoría · configuración variable" detail="PageSpeed requiere PAGESPEED_API_KEY; CrUX requiere CRUX_API_KEY; el crawler propio usa SITE_URL." /></Card></div>; }
