import { ArrowRight, CheckCircle2, FileSearch, LayoutGrid, Search, SlidersHorizontal } from "lucide-react";
import { DashboardShell } from "@/components/dashboard-shell";
import { Bars, Donut, LineChart } from "@/components/charts";
import { alerts, contentItems, keywords, technicalIssues, traffic } from "@/lib/mock-data";
import { Card, CardHeader, Change, DemoBadge, EmptyState, FilterBar, SectionHeading, StatusPill } from "@/components/ui";

const titles: Record<string, [string, string, string]> = {
  "search-console": ["Search Console", "Rendimiento de búsqueda orgánica", "Consulta clicks, impresiones y oportunidades de visibilidad."],
  analytics: ["Analytics", "El tráfico que mueve el negocio", "Sesiones, engagement y conversiones atribuidas al canal orgánico."],
  indexacion: ["Indexación", "Cobertura del sitio", "Entiende qué URLs puede descubrir y servir Google."],
  "auditoria-tecnica": ["Auditoría técnica", "La salud detrás del ranking", "Issues priorizados para mantener una base técnica sólida."],
  keywords: ["Keywords", "El lenguaje de tu audiencia", "Keywords prioritarias por idioma y oportunidad de crecimiento."],
  contenido: ["Contenido", "Contenido que encuentra a las personas", "Una vista editorial de las piezas que sostienen tu estrategia SEO."],
  alertas: ["Alertas", "Señales para actuar a tiempo", "Un centro de control para cambios relevantes y tareas SEO."],
  configuracion: ["Configuración", "Personaliza tu centro de control", "Conexiones y preferencias estarán disponibles en la siguiente fase."],
};

export default async function SectionPage({ params }: { params: Promise<{ section: string }> }) {
  const { section } = await params; const [label, title, description] = titles[section] ?? titles.configuracion;
  return <DashboardShell><SectionHeading eyebrow={label} title={title} description={description} action={<DemoBadge />} />{section === "search-console" && <SearchConsole />}{section === "analytics" && <Analytics />}{section === "indexacion" && <Indexing />}{section === "auditoria-tecnica" && <TechnicalAudit />}{section === "keywords" && <Keywords />}{section === "contenido" && <Content />}{section === "alertas" && <Alerts />}{section === "configuracion" && <Configuration />}</DashboardShell>;
}

function SearchConsole() { return <><FilterBar /><div className="mini-kpis"><Metric label="Clics" value="24.860" change="+18,4%" /><Metric label="Impresiones" value="1,24 M" change="+12,8%" /><Metric label="CTR medio" value="2,01%" change="+0,24 pp" /><Metric label="Posición media" value="11,8" change="-2,1" /></div><Card><div className="tabs"><button className="selected">Consultas</button><button>Páginas</button><button>Países</button><button>Dispositivos</button></div><CardHeader title="Consultas principales" detail="Datos demo · comparación con periodo anterior" action={<button className="outline-button small"><SlidersHorizontal size={14} /> Columnas</button>} /><DataTable headers={["Consulta", "Clics", "Impresiones", "CTR", "Posición"]} rows={keywords.map((k) => [k.keyword, k.clicks, k.impressions, k.ctr, k.position])} /></Card></>; }

function Analytics() { return <><FilterBar /><div className="mini-kpis"><Metric label="Sesiones orgánicas" value="31.420" change="+15,6%" /><Metric label="Usuarios" value="26.180" change="+12,4%" /><Metric label="Engagement" value="64,8%" change="+4,1 pp" /><Metric label="Conversiones" value="846" change="+9,2%" /></div><div className="dashboard-grid"><Card className="wide-card"><CardHeader title="Sesiones orgánicas" detail="Evolución diaria" /><LineChart values={traffic} color="#002DF0" /></Card><Card><CardHeader title="Canales orgánicos" detail="Mix de adquisición" /><Bars values={[74, 58, 42, 29, 18]} color="#0266F2" /><div className="bar-legend"><span>Google <b>62%</b></span><span>Bing <b>18%</b></span><span>Directo asistido <b>12%</b></span></div></Card></div><Card><CardHeader title="Conversiones por objetivo" detail="Atribución demo" /><DataTable headers={["Objetivo", "Completadas", "Tasa"]} rows={[["Solicitud de diagnóstico", "384", "1,22%"], ["Descarga de recurso", "278", "0,88%"], ["Contacto comercial", "184", "0,59%"]]} /></Card></>; }

function Indexing() { return <><div className="indexing-hero"><Card><div className="index-score"><Donut value={84} label="URLs válidas" /><div><span className="eyebrow">Cobertura demo</span><strong>1.284 <small>URLs válidas</small></strong><Change value="+4,6% vs. periodo anterior" /></div></div></Card><div className="index-stat-grid"><Metric label="Indexadas" value="1.284" change="+4,6%" /><Metric label="No indexadas" value="164" change="-8,2%" /><Metric label="Redirecciones" value="48" change="+2,1%" /><Metric label="Errores" value="12" change="-14,3%" /></div></div><Card><CardHeader title="Distribución de cobertura" detail="Estado de URLs detectadas en el sitemap" /><div className="coverage-list"><Coverage label="Indexadas" value="84%" count="1.284" tone="aqua" /><Coverage label="Excluidas correctamente" value="9%" count="136" tone="violet" /><Coverage label="Pendientes de revisión" value="5%" count="76" tone="orange" /><Coverage label="Errores" value="2%" count="12" tone="pink" /></div></Card><Card><EmptyState title="Integración de inspección pendiente" detail="Conecta Search Console para revisar cobertura URL a URL en la siguiente fase." /></Card></>; }

function TechnicalAudit() { return <><div className="audit-toolbar"><div className="filter-chips"><button className="active">Todos <b>5</b></button><button>Alta <b>2</b></button><button>Media <b>2</b></button><button>Baja <b>1</b></button></div><button className="outline-button small"><FileSearch size={14} /> Último rastreo: hoy</button></div><Card><div className="table-scroll"><table><thead><tr><th>Issue</th><th>Categoría</th><th>Afectadas</th><th>Severidad</th><th>Estado</th><th /></tr></thead><tbody>{technicalIssues.map((item) => <tr key={item.issue}><td><b>{item.issue}</b></td><td>{item.category}</td><td>{item.affected}</td><td><StatusPill tone={item.severity.toLowerCase()}>{item.severity}</StatusPill></td><td><StatusPill tone={item.status === "Resuelto" ? "success" : "neutral"}>{item.status}</StatusPill></td><td><button className="icon-button"><ArrowRight size={16} /></button></td></tr>)}</tbody></table></div></Card></>; }

function Keywords() { return <><div className="keyword-callout"><div className="callout-icon"><Search size={20} /></div><div><strong>Oportunidades detectadas</strong><p>12 keywords demo están a menos de 3 posiciones del Top 10.</p></div><button className="text-button">Ver oportunidades <ArrowRight size={14} /></button></div><Card><CardHeader title="Keywords prioritarias" detail="Términos reales de Whalemate · métricas de demostración" action={<div className="search-field"><Search size={15} /><input placeholder="Buscar keyword" aria-label="Buscar keyword" /></div>} /><div className="table-scroll"><table><thead><tr><th>Keyword</th><th>URL</th><th>Idioma</th><th>Posición</th><th>Clics</th><th>Impresiones</th><th>CTR</th><th>Estado</th></tr></thead><tbody>{keywords.map((item) => <tr key={item.keyword}><td><b>{item.keyword}</b></td><td className="url-cell">{item.url}</td><td><span className="language">{item.language}</span></td><td><strong>{item.position}</strong></td><td>{item.clicks}</td><td>{item.impressions}</td><td>{item.ctr}</td><td><StatusPill tone={item.status === "Top 5" ? "success" : item.status === "Oportunidad" ? "orange" : "violet"}>{item.status}</StatusPill></td></tr>)}</tbody></table></div></Card></>; }

function Content() { return <><div className="content-summary"><Metric label="Piezas publicadas" value="48" change="+6 este mes" /><Metric label="Optimización media" value="83/100" change="+5 pts" /><Metric label="Oportunidades" value="9" change="-2" /></div><Card><CardHeader title="Biblioteca de contenido" detail="Blog, podcast y casos de éxito" action={<button className="outline-button small"><LayoutGrid size={14} /> Vista tabla</button>} /><div className="table-scroll"><table><thead><tr><th>Contenido</th><th>Tipo</th><th>Idioma</th><th>Estado SEO</th><th>Score</th><th>Actualizado</th></tr></thead><tbody>{contentItems.map((item) => <tr key={item.title}><td><b>{item.title}</b></td><td>{item.type}</td><td><span className="language">{item.language}</span></td><td><StatusPill tone={item.score > 85 ? "success" : item.score > 70 ? "violet" : "orange"}>{item.status}</StatusPill></td><td><strong className={item.score > 85 ? "score-good" : "score-watch"}>{item.score}</strong></td><td>{item.updated}</td></tr>)}</tbody></table></div></Card></>; }

function Alerts() { return <><div className="alert-overview"><Metric label="Alertas abiertas" value="4" change="-2 esta semana" /><Metric label="Alta prioridad" value="1" change="-1" /><Metric label="Resueltas" value="18" change="+6 este mes" /></div><Card><CardHeader title="Todas las alertas" detail="Cambios y eventos SEO relevantes" action={<button className="outline-button small"><SlidersHorizontal size={14} /> Filtrar</button>} /><div className="full-alert-list">{alerts.map((alert) => <div className="full-alert" key={alert.title}><div className={`alert-symbol ${alert.severity.toLowerCase()}`}>{alert.severity === "Alta" ? "!" : alert.severity === "Media" ? "~" : "✓"}</div><div className="alert-copy"><strong>{alert.title}</strong><span>{alert.detail} · {alert.time}</span></div><StatusPill tone={alert.severity.toLowerCase()}>{alert.severity}</StatusPill><StatusPill tone={alert.status === "Visto" ? "success" : "neutral"}>{alert.status}</StatusPill><button className="text-button">Revisar <ArrowRight size={14} /></button></div>)}</div></Card></>; }

function Configuration() { return <div className="settings-grid"><Card><CardHeader title="Fuentes de datos" detail="Las conexiones se habilitarán en la próxima fase." /><Setting icon="G" title="Google Search Console" detail="Clicks, impresiones, posición e indexación" /><Setting icon="A" title="Google Analytics 4" detail="Sesiones, engagement y conversiones" /><Setting icon="S" title="Screaming Frog / auditoría" detail="Rastreo técnico del sitio" /></Card><Card><CardHeader title="Preferencias" detail="Configura cómo quieres recibir señales." /><Setting icon="⌁" title="Frecuencia de alertas" detail="Resumen semanal · lunes 09:00" /><Setting icon="◎" title="Mercados monitorizados" detail="ES · EN · PT" /><Setting icon="◐" title="Zona horaria" detail="Europe/Madrid (UTC+2)" /></Card><Card className="settings-note"><CheckCircle2 size={24} /><h3>Todo listo para la siguiente fase</h3><p>El frontend está preparado para conectar fuentes reales sin cambiar la experiencia de navegación.</p><button className="outline-button">Documentación de integración <ArrowRight size={15} /></button></Card></div>; }

function Metric({ label, value, change }: { label: string; value: string; change: string }) { return <Card className="metric-card"><span>{label}</span><strong>{value}</strong><Change value={change} /></Card>; }
function DataTable({ headers, rows }: { headers: string[]; rows: string[][] }) { return <div className="table-scroll"><table><thead><tr>{headers.map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={index}>{row.map((cell, cellIndex) => <td key={cellIndex}>{cellIndex === 0 ? <b>{cell}</b> : cell}</td>)}</tr>)}</tbody></table></div>; }
function Coverage({ label, value, count, tone }: { label: string; value: string; count: string; tone: string }) { return <div className="coverage"><div><span className={`coverage-dot ${tone}`} /><b>{label}</b><small>{count} URLs</small></div><div className="coverage-bar"><i className={tone} style={{ width: value }} /></div><strong>{value}</strong></div>; }
function Setting({ icon, title, detail }: { icon: string; title: string; detail: string }) { return <div className="setting"><span>{icon}</span><div><b>{title}</b><small>{detail}</small></div><StatusPill>Próximamente</StatusPill></div>; }
