"use client";

import { FileSearch, RefreshCw, ShieldAlert } from "lucide-react";
import { useEffect, useState } from "react";
import type { AuditData, AuditDevice, AuditIssue } from "@/lib/audit";
import { Card, CardHeader, DataSourceBadge, EmptyState, StatusPill } from "@/components/ui";
import { DataTable, type TableColumn } from "@/components/data-table";

type HistoryItem = Pick<AuditData, "targetUrl" | "device" | "generatedAt" | "sources"> & { issues: number };
const initial: AuditData = { targetUrl: "https://www.whalemate.com/", device: "mobile", generatedAt: "", sources: { psi: "unavailable", crux: "unavailable", crawler: "unavailable" }, psi: { performance: null, seo: null, accessibility: null, bestPractices: null, lcp: null, cls: null, inp: null, tbt: null, opportunities: [] }, crux: { formFactor: "mobile", origin: "https://www.whalemate.com", available: false, lcp: null, inp: null, cls: null, fcp: null, ttfb: null }, crawler: { httpStatus: null, title: null, metaDescription: null, headings: { h1: [], h2: [], h3: [] }, canonical: null, robotsMeta: null, openGraph: [], jsonLd: 0, internalLinks: 0, imagesWithoutAlt: 0, redirects: [], sitemap: "unavailable", robots: "unavailable", issues: [], evidence: [] }, sitemapUrls: [] };
const tabs = ["Salud técnica", "Rendimiento", "On-page", "Enlaces", "Datos estructurados", "Core Web Vitals", "Historial de auditorías"];
const issueColumns: TableColumn<AuditIssue>[] = [
  { key: "issue", label: "Issue", sortValue: (row) => row.issue, filter: "text", render: (row) => <><b>{row.issue}</b><small>{row.evidence}</small></> },
  { key: "category", label: "Categoría", sortValue: (row) => row.category, filter: "select", options: ["Salud técnica", "On-page", "Enlaces", "Indexación", "Accesibilidad"] },
  { key: "severity", label: "Severidad", sortValue: (row) => row.severity, filter: "select", options: ["Alta", "Media", "Baja"], render: (row) => <StatusPill tone={row.severity.toLowerCase()}>{row.severity}</StatusPill> },
  { key: "status", label: "Estado", sortValue: (row) => row.status, filter: "select", options: ["open", "unavailable"], render: (row) => <StatusPill tone={row.status === "open" ? "warning" : "neutral"}>{row.status === "open" ? "Revisar" : "Unavailable"}</StatusPill> },
  { key: "recommendation", label: "Recomendación", sortValue: (row) => row.recommendation, filter: "text" },
];

export function AuditPanel() {
  const [data, setData] = useState<AuditData>(initial); const [target, setTarget] = useState(initial.targetUrl); const [device, setDevice] = useState<AuditDevice>("mobile"); const [tab, setTab] = useState(tabs[0]); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [history, setHistory] = useState<HistoryItem[]>([]);
  useEffect(() => { const timer = window.setTimeout(() => { try { setHistory(JSON.parse(localStorage.getItem("whalemate-audit-history") || "[]")); } catch { setHistory([]); } }, 0); return () => window.clearTimeout(timer); }, []);
  const run = async () => { setLoading(true); setError(""); try { const response = await fetch(`/api/audit?url=${encodeURIComponent(target)}&device=${device}`, { cache: "no-store" }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || "No se pudo ejecutar la auditoría."); setData(payload); const item: HistoryItem = { targetUrl: payload.targetUrl, device: payload.device, generatedAt: payload.generatedAt, sources: payload.sources, issues: payload.crawler.issues.length }; setHistory((current) => { const next = [item, ...current.filter((old) => !(old.targetUrl === item.targetUrl && old.device === item.device))].slice(0, 12); localStorage.setItem("whalemate-audit-history", JSON.stringify(next)); return next; }); } catch (reason) { setError(reason instanceof Error ? reason.message : "No se pudo ejecutar la auditoría."); } finally { setLoading(false); } };
  const scores = [{ label: "Performance", value: data.psi.performance }, { label: "SEO Lighthouse", value: data.psi.seo }, { label: "Accessibility", value: data.psi.accessibility }, { label: "Best Practices", value: data.psi.bestPractices }];
  const issueList = data.crawler.issues;
  return <div className="audit-panel">
    <div className="audit-controls"><label>URL objetivo<select value={target} onChange={(event) => setTarget(event.target.value)}><option value="https://www.whalemate.com/">https://www.whalemate.com/</option>{data.sitemapUrls.map((url) => <option key={url} value={url}>{url}</option>)}</select></label><label className="audit-url-input"><span>Otra URL del mismo hostname</span><input value={target} onChange={(event) => setTarget(event.target.value)} placeholder="https://www.whalemate.com/ruta" /></label><label>Dispositivo<select value={device} onChange={(event) => setDevice(event.target.value as AuditDevice)}><option value="mobile">Mobile</option><option value="desktop">Desktop</option></select></label><button className="primary-button" onClick={run} disabled={loading}>{loading ? <RefreshCw className="spin" size={15} /> : <FileSearch size={15} />} {loading ? "Ejecutando..." : "Ejecutar auditoría"}</button><button className="outline-button" onClick={run} disabled={loading}><RefreshCw size={14} /> Actualizar</button></div>
    {error && <div className="state-box audit-error"><ShieldAlert size={18} /><strong>No se pudo completar</strong><span>{error}</span></div>}
    <div className="audit-meta"><span><strong>Última actualización:</strong> {data.generatedAt ? new Date(data.generatedAt).toLocaleString("es-ES") : "Sin ejecutar"}</span><span><strong>URL:</strong> {data.targetUrl}</span><span><strong>Dispositivo:</strong> {data.device}</span></div>
    <div className="source-status"><Source label="PageSpeed Insights" status={data.sources.psi} detail="Lighthouse por URL" /><Source label="Chrome UX Report" status={data.sources.crux} detail="Datos reales de usuarios" /><Source label="Auditor propio" status={data.sources.crawler} detail="Una URL, server-side" /></div>
    <div className="tabs audit-tabs" role="tablist">{tabs.map((item) => <button key={item} className={tab === item ? "active" : ""} onClick={() => setTab(item)}>{item}</button>)}</div>
    {tab === "Salud técnica" && <><div className="audit-kpis"><Kpi label="HTTP status" value={data.crawler.httpStatus?.toString() || "Unavailable"} /><Kpi label="Issues detectados" value={issueList.filter((issue) => issue.status === "open").length.toString()} /><Kpi label="Enlaces internos" value={data.crawler.internalLinks.toString()} /><Kpi label="Redirects" value={data.crawler.redirects.length.toString()} /></div><IssueTable rows={issueList} /></>}
    {tab === "Rendimiento" && <><Card><CardHeader title="Scores Lighthouse" detail="PageSpeed Insights · URL individual · escala 0-100" /><div className="score-bars">{scores.map((score) => <Bar key={score.label} label={score.label} value={score.value} max={100} suffix="" />)}</div></Card><Card><CardHeader title="Opportunities y diagnostics" detail="Audits reportadas por Lighthouse" />{data.psi.opportunities.length ? <div className="audit-list">{data.psi.opportunities.map((item) => <div key={item.title}><b>{item.title}</b><span>{item.displayValue || "Sin valor adicional"}</span><StatusPill tone={item.score !== null && item.score < 50 ? "error" : "neutral"}>{item.score === null ? "N/A" : `${item.score}/100`}</StatusPill></div>)}</div> : <EmptyState title="PageSpeed Insights unavailable" detail="Configura PAGESPEED_API_KEY para consultar Lighthouse." />}</Card></>}
    {tab === "On-page" && <DetailGrid items={[["Title", data.crawler.title || "Unavailable"], ["Meta description", data.crawler.metaDescription || "Unavailable"], ["H1", data.crawler.headings.h1.join(" · ") || "0 detectados"], ["H2", data.crawler.headings.h2.length.toString()], ["H3", data.crawler.headings.h3.length.toString()], ["Canonical", data.crawler.canonical || "Unavailable"], ["Robots meta", data.crawler.robotsMeta || "No definida"]]} />}
    {tab === "Enlaces" && <DetailGrid items={[["Enlaces internos", data.crawler.internalLinks.toString()], ["Redirects", data.crawler.redirects.join(" → ") || "Ninguno detectado"], ["Sitemap", data.crawler.sitemap], ["robots.txt", data.crawler.robots], ["Huérfanas / profundidad", "Unavailable · not collected (sin crawl completo)"]]} />}
    {tab === "Datos estructurados" && <DetailGrid items={[["JSON-LD / schema", data.crawler.jsonLd ? `${data.crawler.jsonLd} bloque(s)` : "No detectado"], ["Open Graph", data.crawler.openGraph.length ? `${data.crawler.openGraph.length} propiedades` : "No detectado"]]} />}
    {tab === "Core Web Vitals" && <><Card><CardHeader title="CrUX · datos reales" detail={`${data.crux.origin} · ${data.crux.formFactor}`} action={<DataSourceBadge live={data.sources.crux === "live"} error={data.crux.message} />} /><div className="cwv-grid"><Metric label="LCP" value={data.crux.lcp} suffix="ms" /><Metric label="INP" value={data.crux.inp} suffix="ms" /><Metric label="CLS" value={data.crux.cls} suffix="" /><Metric label="FCP" value={data.crux.fcp} suffix="ms" /><Metric label="TTFB" value={data.crux.ttfb} suffix="ms" /></div>{data.crux.message && <EmptyState title="CrUX unavailable" detail={data.crux.message} />}</Card><Card><CardHeader title="PageSpeed · laboratorio" detail="Lighthouse no representa usuarios reales" /><div className="cwv-grid"><Metric label="LCP" value={data.psi.lcp} suffix="ms" /><Metric label="INP" value={data.psi.inp} suffix="ms" /><Metric label="TBT" value={data.psi.tbt} suffix="ms" /><Metric label="CLS" value={data.psi.cls} suffix="" /></div></Card></>}
    {tab === "Historial de auditorías" && <History rows={history} />}
  </div>;
}
function Source({ label, status, detail }: { label: string; status: string; detail: string }) { return <div className="source-card"><div><b>{label}</b><small>{detail}</small></div><StatusPill tone={status === "live" ? "success" : "neutral"}>{status === "live" ? "Live" : status === "demo" ? "Demo fallback" : "Unavailable"}</StatusPill></div>; }
function Kpi({ label, value }: { label: string; value: string }) { return <Card className="audit-kpi"><span>{label}</span><strong>{value}</strong></Card>; }
function Metric({ label, value, suffix }: { label: string; value: number | null; suffix: string }) { return <div className="cwv-metric"><span>{label}</span><strong>{value === null ? "Unavailable" : `${value}${suffix}`}</strong></div>; }
function Bar({ label, value, max, suffix }: { label: string; value: number | null; max: number; suffix: string }) { return <div className="score-bar"><div><span>{label}</span><b>{value === null ? "Unavailable" : `${value}${suffix ? ` ${suffix}` : ""}`}</b></div><i><em style={{ width: `${value === null ? 0 : Math.min(100, value / max * 100)}%` }} /></i></div>; }
function DetailGrid({ items }: { items: string[][] }) { return <div className="detail-grid">{items.map(([label, value]) => <Card key={label}><span>{label}</span><strong>{value}</strong></Card>)}</div>; }
function IssueTable({ rows }: { rows: AuditIssue[] }) { return <Card><CardHeader title="Issues y recomendaciones" detail="Evidencia, severidad y recomendación · búsqueda, orden y filtros" /><DataTable rows={rows} columns={issueColumns} rowKey={(row) => row.id} label="issues" demo={rows.some((row) => row.status === "unavailable")} /></Card>; }
function History({ rows }: { rows: HistoryItem[] }) { return rows.length ? <Card><CardHeader title="Historial de auditorías" detail="Guardado localmente en este navegador" /><div className="history-list">{rows.map((row) => <div key={`${row.targetUrl}-${row.device}-${row.generatedAt}`}><div><b>{row.targetUrl}</b><small>{new Date(row.generatedAt).toLocaleString("es-ES")} · {row.device} · {row.issues} issues</small></div><span>{Object.entries(row.sources).map(([source, status]) => <StatusPill key={source} tone={status === "live" ? "success" : "neutral"}>{source}: {status}</StatusPill>)}</span></div>)}</div></Card> : <EmptyState title="Sin auditorías todavía" detail="Ejecuta una auditoría para crear el primer registro." />; }
