"use client";

import { AlertTriangle, CheckCircle2, RefreshCw } from "lucide-react";
import { useEffect, useState } from "react";
import type { CSSProperties } from "react";
import type { AuditData, AuditDevice, PageAudit, PsiResult } from "@/lib/audit";
import { Card, CardHeader, EmptyState, StatusPill } from "@/components/ui";

const tabs = ["Resumen de salud técnica", "PageSpeed / Lighthouse", "Core Web Vitals", "Indexación GSC", "On-page", "Enlaces/redirects", "Datos estructurados / Schema coverage", "Historial de auditorías"];
const number = (value: number | null) => value === null ? "No data" : value.toLocaleString("es-ES");

export function AuditPanel() {
  const [data, setData] = useState<AuditData | null>(null);
  const [tab, setTab] = useState(tabs[0]);
  const [device, setDevice] = useState<AuditDevice>("mobile");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const run = async () => { if (loading) return; setLoading(true); setError(""); try { const response = await fetch("/api/audit", { cache: "no-store" }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || "Error de conexión"); setData(payload); } catch (reason) { setError(reason instanceof Error ? reason.message : "Error de conexión"); } finally { setLoading(false); } };
  useEffect(() => { void (async () => { setLoading(true); try { const response = await fetch("/api/audit", { cache: "no-store" }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || "Error de conexión"); setData(payload); } catch (reason) { setError(reason instanceof Error ? reason.message : "Error de conexión"); } finally { setLoading(false); } })(); }, []);
  if (loading) return <AuditSkeleton />;
  if (!data) return <div className="audit-panel"><EmptyState title="Error de conexión" detail={error || "La auditoría no pudo responder."} /><button className="primary-button" onClick={() => { setLoading(false); void run(); }}><RefreshCw size={14} /> Reintentar</button></div>;
  const psi = data.devices[device].psi;
  return <div className="audit-panel">
    <div className="audit-toolbar"><div><strong>{new URL(data.siteUrl).hostname}</strong><small>Fuente: dominio fijo · Respuesta: {new Date(data.generatedAt).toLocaleString("es-ES")}</small></div><div className="audit-actions"><label>Vista<select value={device} onChange={(event) => setDevice(event.target.value as AuditDevice)}><option value="mobile">Mobile</option><option value="desktop">Desktop</option></select></label><button className="primary-button" onClick={() => void run()} disabled={loading}><RefreshCw className={loading ? "spin" : ""} size={14} /> Actualizar auditoría</button></div></div>
    {error && <div className="state-box audit-error"><AlertTriangle size={17} /><strong>Error de conexión</strong><span>{error}</span></div>}
    <div className="source-status"><Source label="PageSpeed Insights" status={data.sources.psi} detail="Lighthouse server-side · mobile + desktop" /><Source label="CrUX" status={data.sources.crux} detail="Datos reales de usuarios · origin" /><Source label="Auditor propio" status={data.sources.crawler} detail={`${data.crawler.audited.length} URLs auditadas`} /><Source label="Search Console" status={data.sources.gsc} detail="Sitemap + URL Inspection limitada" /></div>
    <div className="tabs audit-tabs" role="tablist">{tabs.map((item) => <button key={item} className={tab === item ? "active" : ""} onClick={() => setTab(item)}>{item}</button>)}</div>
    {tab === tabs[0] && <Summary data={data} psi={psi} />}
    {tab === tabs[1] && <PageSpeed data={data} device={device} />}
    {tab === tabs[2] && <Vitals data={data} device={device} />}
    {tab === tabs[3] && <Indexing data={data} />}
    {tab === tabs[4] && <OnPage pages={data.crawler.audited} />}
    {tab === tabs[5] && <Links data={data} />}
    {tab === tabs[6] && <Schema data={data} />}
    {tab === tabs[7] && <EmptyState title="No data available" detail="No existe persistencia de historial de auditorías todavía." />}
  </div>;
}
function Source({ label, status, detail }: { label: string; status: string; detail: string }) { return <div className="source-card"><div><b>{label}</b><small>{detail}</small></div><StatusPill tone={status === "live" ? "success" : status === "partial" ? "warning" : "neutral"}>{status === "live" ? "Live" : status === "partial" ? "Partial" : status === "error" ? "Error" : "Unavailable"}</StatusPill></div>; }
function Summary({ data, psi }: { data: AuditData; psi: PsiResult }) { return <><div className="audit-kpis"><Kpi label="URLs sitemap" value={number(data.sitemap.urls.length)} /><Kpi label="URLs auditadas" value={number(data.schema.audited)} /><Kpi label="JSON-LD parseable" value={data.schema.coverage === null ? "No data" : `${data.schema.coverage}%`} /><Kpi label="Issues reales" value={number(data.crawler.issues.length)} /></div><Card><CardHeader title="Salud técnica" detail="Conteos derivados de respuestas reales, sin score inventado." /><div className="health-grid"><Health label="HTTP / metadatos" value={data.crawler.audited.filter((p) => p.status === "live").length ? "Datos disponibles" : "No data"} /><Health label="Robots.txt" value={data.crawler.robots === "live" ? "Disponible" : "Unavailable"} /><Health label="Sitemap" value={data.sitemap.status === "live" ? "Disponible" : "Unavailable"} /><Health label="Schema" value={data.schema.status === "live" || data.schema.status === "partial" ? `${data.schema.withJsonLd} URLs` : "No data"} /></div></Card><Card><CardHeader title="Lighthouse · {device}" detail="Score rings por umbral. Fuente: PageSpeed Insights." /><div className="score-rings">{Object.entries(psi.scores).map(([label, value]) => <ScoreRing key={label} label={label} value={value} />)}</div>{psi.status !== "live" && <EmptyState title="Unavailable" detail={psi.message || "PageSpeed no devolvió datos."} />}</Card></>; }
function PageSpeed({ data, device }: { data: AuditData; device: AuditDevice }) { const psi = data.devices[device].psi; return <><div className="device-switch"><StatusPill tone="neutral">{device}</StatusPill><span>Homepage: {data.siteUrl}</span></div><Card><CardHeader title={`Scores Lighthouse · ${device}`} detail="Laboratorio PageSpeed, no datos de usuarios." /><div className="score-rings">{Object.entries(psi.scores).map(([label, value]) => <ScoreRing key={label} label={label} value={value} />)}</div>{psi.status !== "live" && <EmptyState title="Unavailable" detail={psi.message || "No hay respuesta de PageSpeed."} />}</Card><Card><CardHeader title="Oportunidades y diagnósticos" detail="Ordenados en el orden reportado por Lighthouse." />{psi.opportunities.length ? <div className="audit-list">{psi.opportunities.map((item, index) => <div key={`${item.title}-${index}`}><b>{item.title}</b><span>{item.displayValue || "No data"}</span></div>)}</div> : <EmptyState title="No data" detail="No se recibieron opportunities o diagnostics." />}</Card></>; }
function Vitals({ data, device }: { data: AuditData; device: AuditDevice }) { const lab = data.devices[device].psi; const field = data.devices[device].crux; return <><div className="vitals-source-grid"><MetricCard title="PageSpeed · laboratorio" status={lab.status} metrics={lab.metrics} /><MetricCard title="CrUX · usuarios reales" status={field.status} metrics={field.metrics} /></div><div className="metric-explanation"><strong>Lighthouse y CrUX no son la misma medición.</strong><span>PageSpeed ejecuta una prueba controlada; CrUX agrega experiencias reales. Un valor ausente se muestra como No data.</span></div></>; }
function MetricCard({ title, status, metrics }: { title: string; status: string; metrics: Record<string, number | null> }) { return <Card><CardHeader title={title} detail={`Estado: ${status}`} /><div className="cwv-grid">{Object.entries(metrics).map(([key, value]) => <div className="cwv-metric" key={key}><span>{key.toUpperCase()}</span><strong>{value === null ? "No data" : `${value}${key === "cls" ? "" : " ms"}`}</strong></div>)}</div></Card>; }
function Indexing({ data }: { data: AuditData }) { const index = data.indexing; return <><div className="audit-kpis"><Kpi label="Sitemap" value={number(index.sitemapUrls)} /><Kpi label="Inspeccionadas" value={number(index.inspected)} /><Kpi label="Indexadas" value={number(index.indexed)} /><Kpi label="Cobertura" value={index.coverage === null ? "No data" : `${index.coverage}%`} /></div><Card><CardHeader title="Estado de indexación" detail={index.message || "Google Search Console · URL Inspection"} />{index.rows.length ? <Table headers={["URL", "Estado", "Canonical declarado", "Canonical Google", "Última inspección"]} rows={index.rows.map((row) => [row.url, row.verdict, row.declaredCanonical || "No data", row.googleCanonical || "No data", row.lastInspection ? new Date(row.lastInspection).toLocaleString("es-ES") : "No data"])} /> : <EmptyState title={index.status === "unavailable" ? "Unavailable" : "No data"} detail={index.message || "No se inspeccionaron URLs."} />}</Card></>; }
function OnPage({ pages }: { pages: PageAudit[] }) { return <Card><CardHeader title="On-page por URL" detail="Datos del crawler propio para URLs reales del sitemap." />{pages.length ? <Table headers={["URL", "HTTP", "Title", "Meta description", "H1", "Canonical", "Robots"]} rows={pages.map((p) => [p.url, p.httpStatus?.toString() || "No data", p.title || "No data", p.metaDescription || "No data", p.h1.join(" · ") || "No data", p.canonical || "No data", p.robotsMeta || "No data"])} /> : <EmptyState title="No data" detail="El crawl no devolvió URLs." />}</Card>; }
function Links({ data }: { data: AuditData }) { return <><div className="audit-kpis"><Kpi label="URLs auditadas" value={number(data.crawler.audited.length)} /><Kpi label="Enlaces internos" value={number(data.crawler.audited.reduce((sum, p) => sum + (p.internalLinks || 0), 0))} /><Kpi label="Redirects" value={number(data.crawler.audited.reduce((sum, p) => sum + p.redirects.length, 0))} /><Kpi label="Sin ALT" value={number(data.crawler.audited.reduce((sum, p) => sum + (p.imagesWithoutAlt || 0), 0))} /></div><Card><CardHeader title="Sitemap y robots" detail="Estado real de las fuentes de rastreo." /><div className="detail-grid"><Kpi label="Sitemaps encontrados" value={number(data.sitemap.sitemaps.length)} /><Kpi label="Robots.txt" value={data.crawler.robots === "live" ? "Disponible" : "Unavailable"} /><Kpi label="Sitemap" value={data.sitemap.status === "live" ? "Disponible" : "Unavailable"} /></div></Card></>; }
function Schema({ data }: { data: AuditData }) { return <><div className="audit-kpis"><Kpi label="Auditadas" value={number(data.schema.audited)} /><Kpi label="Con JSON-LD" value={number(data.schema.withJsonLd)} /><Kpi label="Sin JSON-LD" value={number(data.schema.withoutJsonLd)} /><Kpi label="Cobertura" value={data.schema.coverage === null ? "No data" : `${data.schema.coverage}%`} /></div><Card><CardHeader title="Cobertura por tipo" detail={data.schema.message} />{Object.keys(data.schema.byType).length ? <Table headers={["Tipo schema detectado", "URLs / bloques encontrados"]} rows={Object.entries(data.schema.byType).map(([type, count]) => [type, count.toString()])} /> : <EmptyState title="No data" detail="No se detectó JSON-LD parseable en las URLs auditadas." />}</Card><Card><CardHeader title="URLs sin schema" detail="No se inventan URLs: solo aparecen respuestas del sitemap." />{data.schema.withoutSchema.length ? <Table headers={["URL", "Idioma", "Plantilla"]} rows={data.crawler.audited.filter((p) => data.schema.withoutSchema.includes(p.url)).map((p) => [p.url, p.language, p.template])} /> : <EmptyState title="No data" detail="No hay URLs sin JSON-LD en esta muestra." />}</Card><Card><CardHeader title="Errores de parseo" detail="Parseable no significa validado por Google Rich Results." />{data.schema.parseErrors.length ? <Table headers={["URL", "Error"]} rows={data.schema.parseErrors.map((row) => [row.url, row.error])} /> : <EmptyState title="No data" detail="No se registraron errores de parseo." />}</Card></>; }
function ScoreRing({ label, value }: { label: string; value: number | null }) { const color = value === null ? "#dce7e9" : value >= 90 ? "#16805b" : value >= 50 ? "#a86200" : "#c83d2f"; return <div className="score-ring" style={{ "--score": `${value ?? 0}%`, "--ring": color } as CSSProperties} aria-label={`${label}: ${value === null ? "No data" : value}`}><div><strong>{value ?? "—"}</strong><span>{label}</span></div></div>; }
function Kpi({ label, value }: { label: string; value: string }) { return <Card className="audit-kpi"><span>{label}</span><strong>{value}</strong></Card>; }
function Health({ label, value }: { label: string; value: string }) { return <div className="health-item"><CheckCircle2 size={16} /><span>{label}</span><b>{value}</b></div>; }
function Table({ headers, rows }: { headers: string[]; rows: string[][] }) { return <div className="table-scroll"><table><thead><tr>{headers.map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={index}>{row.map((cell, cellIndex) => <td key={cellIndex}>{cell}</td>)}</tr>)}</tbody></table></div>; }
function AuditSkeleton() { return <div className="audit-panel"><div className="audit-skeleton" aria-label="Cargando auditoría"><i /><i /><i /><i /><i /><i /></div></div>; }
