"use client";

import Image from "next/image";
import Link from "next/link";
import { Suspense, useState } from "react";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { BarChart3, Bell, ChevronDown, FileText, LayoutDashboard, Menu, ScanSearch, Search, Settings2, ShieldCheck, Target, X } from "lucide-react";
import type { IntegrationFilters } from "@/lib/integrations";
import { FilterContext, type FilterContextValue } from "./filter-context";

const navItems = [{ href: "/", label: "Resumen", icon: LayoutDashboard }, { href: "/search-console", label: "Search Console", icon: Search }, { href: "/analytics", label: "Analytics", icon: BarChart3 }, { href: "/indexacion", label: "Indexación", icon: ScanSearch }, { href: "/auditoria-tecnica", label: "Auditoría técnica", icon: ShieldCheck }, { href: "/keywords", label: "Keywords", icon: Target }, { href: "/contenido", label: "Contenido", icon: FileText }, { href: "/alertas", label: "Alertas", icon: Bell }, { href: "/configuracion", label: "Configuración", icon: Settings2 }] as const;
export function DashboardShell({ children }: { children: React.ReactNode }) { return <Suspense fallback={<div className="state-box">Cargando dashboard...</div>}><DashboardContent>{children}</DashboardContent></Suspense>; }
function DashboardContent({ children }: { children: React.ReactNode }) { const [open, setOpen] = useState(false); const pathname = usePathname(); const searchParams = useSearchParams(); const router = useRouter(); const [refreshKey, setRefreshKey] = useState(0); const rawDays = Number(searchParams.get("days")); const filters: IntegrationFilters = { days: ([7, 28, 60, 90].includes(rawDays) ? rawDays : 28) as IntegrationFilters["days"], language: (searchParams.get("language") ?? "all") as IntegrationFilters["language"], country: searchParams.get("country") ?? "all", device: (searchParams.get("device") ?? "all") as IntegrationFilters["device"], page: searchParams.get("page") ?? undefined, query: searchParams.get("query") ?? undefined }; const updateFilter = (key: keyof IntegrationFilters, value: string) => { const next = new URLSearchParams(searchParams.toString()); if (!value || value === "all") next.delete(key); else next.set(key, value); router.replace(`${pathname}${next.toString() ? `?${next.toString()}` : ""}`, { scroll: false }); }; const context: FilterContextValue = { filters, refreshKey, updateFilter, refresh: () => setRefreshKey((value) => value + 1) }; return <FilterContext.Provider value={context}><div className="app-shell"><aside className={`sidebar ${open ? "open" : ""}`}><div className="brand"><Image src="/whalemate-logo-header.webp" alt="whalemate" width={195} height={30} priority /><button className="icon-button mobile-close" aria-label="Cerrar menú" onClick={() => setOpen(false)}><X size={18} /></button></div><div className="workspace"><span className="workspace-avatar">W</span><span><b>Whalemate</b><small>Fuentes reales</small></span><ChevronDown size={15} /></div><nav aria-label="Navegación principal">{navItems.map(({ href, label, icon: Icon }) => <Link key={href} href={href} className={href === "/" ? pathname === "/" ? "active" : "" : pathname.startsWith(href) ? "active" : ""} onClick={() => setOpen(false)}><Icon size={18} /><span>{label}</span></Link>)}</nav><div className="sidebar-bottom"><div className="sync-note"><span className="live-dot" /> Datos de APIs reales <small>El estado se indica en cada panel</small></div></div></aside><main className="main-content"><header className="topbar"><button className="icon-button menu-button" aria-label="Abrir menú" onClick={() => setOpen(true)}><Menu size={20} /></button><Image className="topbar-logo" src="/whalemate-logo-header.webp" alt="whalemate" width={195} height={30} priority /><div className="breadcrumb"><span>Whalemate</span><b>/</b><strong>{navItems.find((item) => item.href === pathname)?.label ?? "Resumen"}</strong></div><div className="top-actions" /></header><div className="page-content">{children}</div></main></div></FilterContext.Provider>; }
