"use client";

import { useEffect, useState } from "react";
import { Card, CardHeader, Change, DataSourceBadge, EmptyState, LoadingState } from "@/components/ui";
import { useDashboardFilters } from "./filter-context";
import type { AnalyticsData, IntegrationResponse, SearchConsoleData } from "@/lib/integrations";
import { DataTable, type TableColumn } from "./data-table";

const emptySearch: SearchConsoleData = { period: { start: "", end: "", previousStart: "", previousEnd: "" }, metrics: { clicks: null, impressions: null, ctr: null, position: 0 }, previous: { clicks: null, impressions: null, ctr: null, position: 0 }, queries: [], pages: [], opportunities: { positions4to10: [], positions11to20: [] } };
const emptyAnalytics: AnalyticsData = { period: { start: "", end: "", previousStart: "", previousEnd: "" }, metrics: { users: null, newUsers: null, sessions: null, organicSessions: null, aiSessions: null, engagedSessions: null, engagementRate: null, engagementDuration: null, eventCount: null, conversions: null }, previous: { users: null, newUsers: null, sessions: null, organicSessions: null, aiSessions: null, engagedSessions: null, engagementRate: null, engagementDuration: null, eventCount: null, conversions: null }, landingPages: [], sources: [], aiSources: [], aiLandingPages: [], countries: [], devices: [], dailySessions: [], aiStatus: "unavailable", warnings: [] };
const number = (value: number | null | undefined, available: boolean) => available && value != null ? new Intl.NumberFormat("es-ES", { maximumFractionDigits: 0 }).format(value) : "No data";
const percent = (value: number | null | undefined, available: boolean) => available && value != null ? `${(value * 100).toFixed(2).replace(".", ",")}%` : "No data";
const emptyResponse = <T,>(data: T, error: string): IntegrationResponse<T> => ({ status: "unavailable", data, error, generatedAt: "" });

function useIntegration<T>(endpoint: string, initial: T) { const { filters, refreshKey } = useDashboardFilters(); const [response, setResponse] = useState<IntegrationResponse<T> | null>(null); const [loadedUrl, setLoadedUrl] = useState(""); const params = new URLSearchParams({ days: String(filters.days), language: filters.language, country: filters.country, device: filters.device }); if (filters.page) params.set("page", filters.page); if (filters.query) params.set("query", filters.query); const url = `${endpoint}?${params.toString()}`; useEffect(() => { const controller = new AbortController(); fetch(url, { cache: "no-store", signal: controller.signal }).then((result) => result.json()).then((value) => { setResponse(value); setLoadedUrl(url); }).catch((error) => { if (error.name !== "AbortError") { setResponse(emptyResponse(initial, "No se pudo conectar con la fuente.")); setLoadedUrl(url); } }); return () => controller.abort(); }, [url, refreshKey, initial]); return { response: response ?? emptyResponse(initial, "Consultando la fuente."), loading: loadedUrl !== url }; }
function Metric({ label, value, change }: { label: string; value: string; change: string }) { return <Card className="metric-card"><span>{label}</span><strong>{value}</strong><Change value={change} trend="steady" /></Card>; }
function Verification({ response, source }: { response: IntegrationResponse<SearchConsoleData | AnalyticsData>; source: string }) { const available = response.status === "live"; return <div className="verification"><strong>Fuente</strong><span>{source} · {available ? "Live" : response.status === "no_data" ? "No data" : "Unavailable"}{response.metadata ? ` · ${response.metadata.rows} filas recibidas` : ""}</span>{response.data.period.start && response.data.period.end ? <span>Periodo consultado: {response.data.period.start} — {response.data.period.end}</span> : null}</div>; }
function State({ response }: { response: IntegrationResponse<unknown> }) { return response.status === "live" ? null : <EmptyState title={response.status === "no_data" ? "No data available" : "Unavailable"} detail={response.error ?? "La fuente no está conectada o no devolvió datos."} />; }

export function SearchConsoleLive() { const { response, loading } = useIntegration("/api/integrations/search-console", emptySearch); if (loading) return <LoadingState />; const { data } = response; const live = response.status === "live"; const queryColumns: TableColumn<SearchConsoleData["queries"][number]>[] = [{ key: "query", label: "Query", sortValue: (row) => row.query, filter: "text" }, { key: "clicks", label: "Clicks", sortValue: (row) => row.clicks, filter: "number", render: (row) => number(row.clicks, live) }, { key: "impressions", label: "Impresiones", sortValue: (row) => row.impressions, filter: "number", render: (row) => number(row.impressions, live) }, { key: "ctr", label: "CTR", sortValue: (row) => row.ctr, filter: "number", render: (row) => percent(row.ctr, live) }, { key: "position", label: "Posición", sortValue: (row) => row.position, filter: "number", render: (row) => live ? row.position.toFixed(1).replace(".", ",") : "—" }]; const pageColumns: TableColumn<SearchConsoleData["pages"][number]>[] = [{ key: "page", label: "Organic path", sortValue: (row) => row.page, filter: "text" }, { key: "clicks", label: "Clicks", sortValue: (row) => row.clicks, filter: "number", render: (row) => number(row.clicks, live) }, { key: "impressions", label: "Impresiones", sortValue: (row) => row.impressions, filter: "number", render: (row) => number(row.impressions, live) }, { key: "ctr", label: "CTR", sortValue: (row) => row.ctr, filter: "number", render: (row) => percent(row.ctr, live) }, { key: "position", label: "Posición", sortValue: (row) => row.position, filter: "number", render: (row) => live ? row.position.toFixed(1).replace(".", ",") : "—" }, { key: "language", label: "Idioma", sortValue: (row) => row.language, filter: "select", options: ["ES", "EN", "PT"] }]; return <><div className="mini-kpis"><Metric label="Clicks orgánicos · GSC" value={number(data.metrics.clicks, live)} change="Datos de la fuente" /><Metric label="Impresiones · GSC" value={number(data.metrics.impressions, live)} change="Datos de la fuente" /><Metric label="CTR medio · GSC" value={percent(data.metrics.ctr, live)} change="Datos de la fuente" /><Metric label="Posición media · GSC" value={live ? data.metrics.position.toFixed(1).replace(".", ",") : "—"} change="Datos de la fuente" /></div><State response={response} /><Card><CardHeader title="Top queries" detail="Search Console · resultados reales" action={<DataSourceBadge live={live} error={response.error} />} /><DataTable rows={data.queries} columns={queryColumns} rowKey={(row) => row.query} label="queries" /></Card><Card><CardHeader title="Top organic paths" detail="Search Console · páginas reales" /><DataTable rows={data.pages} columns={pageColumns} rowKey={(row) => row.page} label="organic paths" /></Card><Verification response={response} source="Search Console" /></>; }

export function AnalyticsLive() { const { response, loading } = useIntegration("/api/integrations/analytics", emptyAnalytics); if (loading) return <LoadingState />; const { data } = response; const live = response.status === "live"; const columns: TableColumn<AnalyticsData["sources"][number]>[] = [{ key: "name", label: "Fuente / dimensión", sortValue: (row) => row.name, filter: "text" }, { key: "sessions", label: "Sesiones", sortValue: (row) => row.sessions, filter: "number", render: (row) => number(row.sessions, live) }, { key: "users", label: "Usuarios", sortValue: (row) => row.users, filter: "number", render: (row) => number(row.users, live) }, { key: "conversions", label: "Conversiones", sortValue: (row) => row.conversions, filter: "number", render: (row) => number(row.conversions, live) }, { key: "engagementRate", label: "Engagement", sortValue: (row) => row.engagementRate, filter: "number", render: (row) => percent(row.engagementRate, live) }]; return <><div className="metric-explanation"><strong>GA4 Analytics</strong><span>Datos exclusivamente de Google Analytics Data API.</span></div><div className="mini-kpis"><Metric label="Usuarios" value={number(data.metrics.users, live)} change="Datos de la fuente" /><Metric label="Usuarios nuevos" value={number(data.metrics.newUsers, live)} change="Datos de la fuente" /><Metric label="Sesiones" value={number(data.metrics.sessions, live)} change="Datos de la fuente" /><Metric label="Sesiones orgánicas" value={number(data.metrics.organicSessions, live)} change="Datos de la fuente" /><Metric label="Sesiones con interacción" value={number(data.metrics.engagedSessions, live)} change="Datos de la fuente" /><Metric label="Tasa de interacción" value={percent(data.metrics.engagementRate, live)} change="Datos de la fuente" /><Metric label="Eventos" value={number(data.metrics.eventCount, live)} change="Datos de la fuente" /><Metric label="Conversiones" value={number(data.metrics.conversions, live)} change="Datos de la fuente" /></div><State response={response} /><Card><CardHeader title="Fuentes y dimensiones" detail="GA4 · resultados reales" action={<DataSourceBadge live={live} error={response.error} />} /><DataTable rows={data.sources} columns={columns} rowKey={(row) => row.name} label="fuentes" /></Card><Verification response={response} source="Google Analytics 4" /></>; }
export function SummaryLive() { const search = useIntegration("/api/integrations/search-console", emptySearch); const analytics = useIntegration("/api/integrations/analytics", emptyAnalytics); if (search.loading || analytics.loading) return <LoadingState />; const live = search.response.status === "live" && analytics.response.status === "live"; return <><div className="integration-summary"><DataSourceBadge live={live} error={search.response.error || analytics.response.error} /><span>{live ? "Conexiones reales activas" : "No data available · conecta GSC y GA4 para mostrar métricas"}</span></div><div className="mini-kpis"><Metric label="Clicks orgánicos · GSC" value={number(search.response.data.metrics.clicks, search.response.status === "live")} change="Fuente GSC" /><Metric label="Impresiones · GSC" value={number(search.response.data.metrics.impressions, search.response.status === "live")} change="Fuente GSC" /><Metric label="Sesiones · GA4" value={number(analytics.response.data.metrics.sessions, analytics.response.status === "live")} change="Fuente GA4" /><Metric label="Conversiones · GA4" value={number(analytics.response.data.metrics.conversions, analytics.response.status === "live")} change="Fuente GA4" /></div><State response={search.response} /><State response={analytics.response} /><Verification response={search.response} source="Search Console" /><Verification response={analytics.response} source="Google Analytics 4" /></>; }
