"use client";

import { useEffect, useState } from "react";
import { Card, CardHeader, Change, DataSourceBadge, EmptyState, LoadingState } from "@/components/ui";
import { useDashboardFilters } from "./filter-context";
import type { AnalyticsData, IntegrationResponse, SearchConsoleData } from "@/lib/integrations";
import type { KeywordsData, KeywordRow } from "@/lib/keywords";
import { DataTable, type TableColumn } from "./data-table";

const emptySearch: SearchConsoleData = { period: { start: "", end: "", previousStart: "", previousEnd: "" }, metrics: { clicks: null, impressions: null, ctr: null, position: 0 }, previous: { clicks: null, impressions: null, ctr: null, position: 0 }, queries: [], pages: [], opportunities: { positions4to10: [], positions11to20: [] } };
const emptyAnalytics: AnalyticsData = { period: { start: "", end: "", previousStart: "", previousEnd: "" }, metrics: { users: null, newUsers: null, sessions: null, organicSessions: null, aiSessions: null, engagedSessions: null, engagementRate: null, engagementDuration: null, eventCount: null, conversions: null }, previous: { users: null, newUsers: null, sessions: null, organicSessions: null, aiSessions: null, engagedSessions: null, engagementRate: null, engagementDuration: null, eventCount: null, conversions: null }, landingPages: [], sources: [], aiSources: [], aiLandingPages: [], countries: [], devices: [], dailySessions: [], aiStatus: "unavailable", warnings: [] };
const emptyKeywords: KeywordsData = { period: { start: "", end: "", previousStart: "", previousEnd: "" }, rows: [], winners: [], losers: [], opportunities: [], cannibalization: [] };
type SummaryData = { period: { start: string; end: string; previousStart: string; previousEnd: string }; metrics: { searchConsole: SearchConsoleData["metrics"] | null; analytics: AnalyticsData["metrics"] | null }; previous: { searchConsole: SearchConsoleData["previous"] | null; analytics: AnalyticsData["previous"] | null }; keywords: { winning: SearchConsoleData["queries"]; losing: SearchConsoleData["queries"] }; indexation: { problemUrls?: string[] } | null; technical: { status?: string; issues?: unknown[] } | null };
const emptySummary: SummaryData = { period: { start: "", end: "", previousStart: "", previousEnd: "" }, metrics: { searchConsole: null, analytics: null }, previous: { searchConsole: null, analytics: null }, keywords: { winning: [], losing: [] }, indexation: null, technical: null };
const number = (value: number | null | undefined, live: boolean) => live && value != null ? new Intl.NumberFormat("es-ES", { maximumFractionDigits: 0 }).format(value) : "No data";
const percent = (value: number | null | undefined, live: boolean) => live && value != null ? `${(value * 100).toFixed(2).replace(".", ",")}%` : "No data";
const emptyResponse = <T,>(data: T, error: string): IntegrationResponse<T> => ({ status: "unavailable", data, error, generatedAt: "" });

function useIntegration<T>(endpoint: string, initial: T, extra = "") {
  const { filters, refreshKey } = useDashboardFilters();
  const [response, setResponse] = useState<IntegrationResponse<T> | null>(null);
  const [loadedUrl, setLoadedUrl] = useState("");
  const params = new URLSearchParams({ days: String(filters.days), language: filters.language, country: filters.country, device: filters.device });
  if (filters.page) params.set("page", filters.page);
  if (filters.query) params.set("query", filters.query);
  const url = `${endpoint}?${params.toString()}${extra ? `&${extra}` : ""}`;
  useEffect(() => { const controller = new AbortController(); fetch(url, { cache: "no-store", signal: controller.signal }).then((result) => result.json()).then((value) => { setResponse(value); setLoadedUrl(url); }).catch((error) => { if (error.name !== "AbortError") { setResponse(emptyResponse(initial, "No se pudo conectar con la fuente.")); setLoadedUrl(url); } }); return () => controller.abort(); }, [url, refreshKey, initial]);
  return { response: response ?? emptyResponse(initial, "Consultando la fuente."), loading: loadedUrl !== url };
}

function Metric({ label, value, change = "Fuente conectada" }: { label: string; value: string; change?: string }) { return <Card className="metric-card"><span>{label}</span><strong>{value}</strong><Change value={change} trend="steady" /></Card>; }
function State({ response }: { response: IntegrationResponse<unknown> }) { return response.status === "live" ? null : <EmptyState title={response.status === "no_data" ? "No data available" : "Unavailable"} detail={response.error ?? "La fuente no está conectada o no devolvió datos."} />; }
function Verification({ response, source }: { response: IntegrationResponse<{ period: { start: string; end: string } }>; source: string }) { return <div className="verification"><DataSourceBadge live={response.status === "live"} error={response.error} /><span>{source}{response.generatedAt ? ` · ${new Date(response.generatedAt).toLocaleString("es-ES")}` : ""}</span>{response.data.period.start && <span>{response.data.period.start} — {response.data.period.end}</span>}</div>; }

export function SummaryLive() {
  const { response, loading } = useIntegration<SummaryData>("/api/summary", emptySummary);
  if (loading) return <LoadingState />;
  const payload = response;
  const data = payload.data ?? emptySummary;
  const gsc = data?.metrics.searchConsole; const ga = data?.metrics.analytics;
  const change = (current: number | null | undefined, previous: number | null | undefined) => current != null && previous != null ? `${current >= previous ? "+" : ""}${(current - previous).toFixed(1)}` : "Comparación no disponible";
  return <><div className="integration-summary"><DataSourceBadge live={payload.status === "live"} error={payload.error} /><span>Resumen basado únicamente en snapshots persistidos de GSC y GA4.</span></div><div className="mini-kpis"><Metric label="Clicks orgánicos · GSC" value={number(gsc?.clicks, Boolean(gsc))} change={change(gsc?.clicks, data?.previous.searchConsole?.clicks)} /><Metric label="Impresiones · GSC" value={number(gsc?.impressions, Boolean(gsc))} change={change(gsc?.impressions, data?.previous.searchConsole?.impressions)} /><Metric label="CTR · GSC" value={percent(gsc?.ctr, Boolean(gsc))} change={change(gsc?.ctr, data?.previous.searchConsole?.ctr)} /><Metric label="Posición media · GSC" value={number(gsc?.position, Boolean(gsc))} /><Metric label="Usuarios orgánicos · GA4" value={number(ga?.users, Boolean(ga))} change={change(ga?.users, data?.previous.analytics?.users)} /><Metric label="Sesiones orgánicas · GA4" value={number(ga?.organicSessions, Boolean(ga))} change={change(ga?.organicSessions, data?.previous.analytics?.organicSessions)} /><Metric label="Conversiones · GA4" value={number(ga?.conversions, Boolean(ga))} change={change(ga?.conversions, data?.previous.analytics?.conversions)} /></div><State response={payload} /><Card><CardHeader title="Keywords ganadoras y perdedoras" detail="Derivadas del snapshot de Search Console." /><div className="analytics-secondary-grid"><MiniRows title="Ganadoras" rows={data?.keywords.winning ?? []} /><MiniRows title="Perdedoras" rows={data?.keywords.losing ?? []} /></div></Card><Card><CardHeader title="Indexación y estado técnico" /> <p>{data?.indexation ? `${data.indexation.problemUrls?.length ?? 0} URLs con problemas de indexación.` : "No data available"}</p><p>{data?.technical ? `Auditoría: ${data.technical.status ?? "available"}.` : "Estado técnico: Unavailable"}</p></Card><Verification response={payload} source={`Snapshot · ${payload.metadata?.snapshotAt ? Object.values(payload.metadata.snapshotAt).filter(Boolean).map((value) => new Date(value as string).toLocaleString("es-ES")).join(" · ") : "timestamp no disponible"}`} /></>;
}
function MiniRows({ title, rows }: { title: string; rows: Array<{ query: string; clicks: number }> }) { return <div><strong>{title}</strong>{rows.length ? <ul>{rows.map((row) => <li key={row.query}><span>{row.query}</span><b>{row.clicks.toLocaleString("es-ES")}</b></li>)}</ul> : <EmptyState title="No data available" />}</div>; }

export function SearchConsoleLive() {
  const [view, setView] = useState("performance");
  const extra = view === "performance" || view === "pages" ? "" : `view=global&segment=${view}`;
  const { response, loading } = useIntegration("/api/integrations/search-console", emptySearch, extra);
  if (loading) return <LoadingState />;
  const live = response.status === "live"; const data = response.data;
  const dimension = data.dimensions?.[view === "brand" ? "brand" : view === "nonBrand" ? "nonBrand" : view as "country" | "device" | "searchType" | "appearance"] ?? [];
  const dimensionColumns: TableColumn<typeof dimension[number]>[] = [{ key: "value", label: "Dimensión", sortValue: (row) => row.value, filter: "text" }, { key: "clicks", label: "Clicks", sortValue: (row) => row.clicks, filter: "number", render: (row) => number(row.clicks, live) }, { key: "impressions", label: "Impresiones", sortValue: (row) => row.impressions, filter: "number", render: (row) => number(row.impressions, live) }, { key: "ctr", label: "CTR", sortValue: (row) => row.ctr, render: (row) => percent(row.ctr, live) }, { key: "position", label: "Posición", sortValue: (row) => row.position, render: (row) => live ? row.position.toFixed(1).replace(".", ",") : "No data" }];
  const pageColumns: TableColumn<SearchConsoleData["pages"][number]>[] = [{ key: "page", label: "Página", sortValue: (row) => row.page, filter: "text" }, { key: "clicks", label: "Clicks", sortValue: (row) => row.clicks, render: (row) => number(row.clicks, live) }, { key: "impressions", label: "Impresiones", sortValue: (row) => row.impressions, render: (row) => number(row.impressions, live) }, { key: "ctr", label: "CTR", sortValue: (row) => row.ctr, render: (row) => percent(row.ctr, live) }, { key: "position", label: "Posición", sortValue: (row) => row.position, render: (row) => live ? row.position.toFixed(1).replace(".", ",") : "No data" }];
  return <><div className="tabs filter-chips">{[["performance", "Rendimiento"], ["pages", "Páginas"], ["country", "Países"], ["device", "Dispositivos"], ["searchType", "Search type"], ["appearance", "Apariencia"], ["brand", "Marca"], ["nonBrand", "No marca"]].map(([key, label]) => <button key={key} className={view === key ? "active" : ""} onClick={() => setView(key)}>{label}</button>)}</div><div className="mini-kpis"><Metric label="Clicks" value={number(data.metrics.clicks, live)} /><Metric label="Impresiones" value={number(data.metrics.impressions, live)} /><Metric label="CTR" value={percent(data.metrics.ctr, live)} /><Metric label="Posición media GSC" value={number(data.metrics.position, live)} /></div><State response={response} /><Verification response={response} source="Search Console" />{view === "performance" && <Card><CardHeader title="Rendimiento orgánico" detail="La tabla de queries + página específica vive exclusivamente en Keywords." /><EmptyState title={live ? "No data available" : "Unavailable"} detail="Usa Páginas o una dimensión global para explorar el rendimiento." /></Card>}{view === "pages" && <Card><CardHeader title="Páginas orgánicas" /><DataTable columns={pageColumns} rows={live ? data.pages : []} label="páginas" /></Card>}{view !== "performance" && view !== "pages" && <Card><CardHeader title={view === "brand" || view === "nonBrand" ? `Marca / no marca · ${view === "brand" ? "Marca" : "No marca"}` : `Search Console · ${view}`} detail="Agregación global de Search Console; no se muestran páginas." /><DataTable columns={dimensionColumns} rows={dimension} label="dimensiones" /></Card>}</>;
}

export function AnalyticsLive() {
  const { response, loading } = useIntegration("/api/integrations/analytics", emptyAnalytics);
  if (loading) return <LoadingState />;
  const live = response.status === "live"; const data = response.data;
  const columns: TableColumn<AnalyticsData["landingPages"][number]>[] = [{ key: "page", label: "Landing page orgánica", sortValue: (row) => row.page, filter: "text" }, { key: "users", label: "Usuarios", sortValue: (row) => row.users, render: (row) => number(row.users, live) }, { key: "sessions", label: "Sesiones", sortValue: (row) => row.sessions, render: (row) => number(row.sessions, live) }, { key: "conversions", label: "Conversiones", sortValue: (row) => row.conversions, render: (row) => number(row.conversions, live) }];
  return <><div className="metric-explanation"><strong>GA4 Analytics</strong><span>Este panel sólo consulta Google Analytics Data API; no mezcla métricas de Search Console.</span></div><div className="mini-kpis"><Metric label="Usuarios" value={number(data.metrics.users, live)} /><Metric label="Sesiones" value={number(data.metrics.sessions, live)} /><Metric label="Sesiones orgánicas" value={number(data.metrics.organicSessions, live)} /><Metric label="Conversiones" value={number(data.metrics.conversions, live)} /></div><State response={response} /><Verification response={response} source="Google Analytics 4" /><Card><CardHeader title="Landing pages orgánicas" /><DataTable columns={columns} rows={live ? data.landingPages : []} label="landing pages" /></Card></>;
}

export function KeywordsLive() {
  const [view, setView] = useState("all"); const { response, loading } = useIntegration("/api/gsc/keywords", emptyKeywords);
  if (loading) return <LoadingState />;
  const live = response.status === "live"; const data = response.data;
  const views: Record<string, KeywordRow[]> = { all: data.rows, target: data.rows.filter((row) => row.keywordTarget), opportunities: data.opportunities, winners: data.winners, losers: data.losers, cannibalization: data.rows.filter((row) => data.cannibalization.some((item) => item.query === row.query)), brand: data.rows.filter((row) => row.brand === "brand"), non_brand: data.rows.filter((row) => row.brand === "non_brand") };
  const columns: TableColumn<KeywordRow>[] = [{ key: "query", label: "Keyword / query", sortValue: (row) => row.query, filter: "text" }, { key: "page", label: "Página", sortValue: (row) => row.page, filter: "text" }, { key: "position", label: "Posición media GSC", sortValue: (row) => row.position, render: (row) => live ? row.position.toFixed(1).replace(".", ",") : "No data" }, { key: "impressions", label: "Impresiones", sortValue: (row) => row.impressions, render: (row) => number(row.impressions, live) }, { key: "ctr", label: "CTR", sortValue: (row) => row.ctr, render: (row) => percent(row.ctr, live) }];
  return <><div className="metric-explanation"><strong>Keywords · Search Console</strong><span>La posición es la media reportada por GSC, no un ranking exacto. Los objetivos no están inventados: si no existe carga de targets, Objetivo queda en No data.</span></div><div className="tabs filter-chips">{[["all", "Todas"], ["target", "Objetivo"], ["opportunities", "Oportunidades"], ["winners", "Ganadoras"], ["losers", "Perdedoras"], ["cannibalization", "Canibalización"], ["brand", "Marca"], ["non_brand", "No marca"]].map(([key, label]) => <button key={key} className={view === key ? "active" : ""} onClick={() => setView(key)}>{label}</button>)}</div><State response={response} /><Verification response={response} source="Search Console · Keywords" /><Card><CardHeader title={view === "target" ? "Keywords objetivo" : "Keywords"} /><DataTable columns={columns} rows={live ? views[view] : []} label="keywords" /></Card>{view === "cannibalization" && <Card><CardHeader title="Queries con más de una página" />{data.cannibalization.length ? <ul>{data.cannibalization.map((item) => <li key={item.query}>{item.query}: {item.pages.join(" · ")}</li>)}</ul> : <EmptyState title="No data available" />}</Card>}</>;
}
