"use client";

import Link from "next/link";
import { Activity, ArrowRight, BarChart3, CheckCircle2, CircleAlert, Gauge, RefreshCw, Search, ShieldCheck } from "lucide-react";
import { useEffect, useState } from "react";
import { Card, EmptyState, LoadingState } from "@/components/ui";
import { useDashboardFilters } from "@/components/filter-context";

type Row = { query: string; position: number | null; previousPosition: number | null; impressions: number | null };
type Payload = { status: string; error?: string; data: { period: { start: string; end: string; previousStart: string; previousEnd: string }; metrics: { analytics: { users: number | null; organicSessions: number | null; engagementRate: number | null; aiSessions: number | null } | null }; previous: { analytics: { users: number | null; organicSessions: number | null; engagementRate: number | null } | null }; overview: { healthScore: number | null; keywordsTop10: number; monthlyActions: number | null; issues: number }; rankings: { top3: number; top10: number; top30: number; noPosition: number; rows: Row[] }; audit: { score: number | null; issues: number; severity: Array<{ severity: string; count: number }>; lastAudit: string | null; vitals: { status: string; metrics: Record<string, number | null> } | null }; sources: Record<string, string>; }; metadata?: { snapshotAt?: Record<string, string | null> } };

const empty: Payload = { status: "unavailable", data: { period: { start: "", end: "", previousStart: "", previousEnd: "" }, metrics: { analytics: null }, previous: { analytics: null }, overview: { healthScore: null, keywordsTop10: 0, monthlyActions: null, issues: 0 }, rankings: { top3: 0, top10: 0, top30: 0, noPosition: 0, rows: [] }, audit: { score: null, issues: 0, severity: [], lastAudit: null, vitals: null }, sources: {} } };
const number = (value: number | null | undefined) => value == null ? "No data" : new Intl.NumberFormat("es-ES", { maximumFractionDigits: 0 }).format(value);
const percent = (value: number | null | undefined) => value == null ? "No data" : `${(value * 100).toFixed(2).replace(".", ",")}%`;
const date = (value: string | null | undefined) => value ? new Date(value).toLocaleDateString("es-ES", { day: "numeric", month: "short", year: "numeric" }) : "No data";

export function SummaryPanel() {
  const { refreshKey } = useDashboardFilters();
  const [payload, setPayload] = useState<Payload | null>(null);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  useEffect(() => { const controller = new AbortController(); fetch("/api/summary", { cache: "no-store", signal: controller.signal }).then(async (response) => { const value = await response.json(); setPayload(value); }).catch((error) => { if (error.name !== "AbortError") setPayload({ ...empty, error: "No se pudo consultar el Resumen." }); }).finally(() => setLoading(false)); return () => controller.abort(); }, [refreshKey]);
  const update = async () => { if (refreshing) return; setRefreshing(true); try { await fetch("/api/ingest?sources=gsc,ga4&refresh=1", { method: "POST" }); window.location.reload(); } finally { setRefreshing(false); } };
  if (loading && !payload) return <LoadingState />;
  const response = payload ?? empty; const data = response.data;
  const ga = data.metrics.analytics; const previous = data.previous.analytics;
  const updated = Object.values(response.metadata?.snapshotAt ?? {}).filter(Boolean).sort().at(-1);
  return <div className="summary-workspace">
    <header className="summary-header"><div><span className="summary-eyebrow">SEO Overview</span><h1>Vista general del estado SEO</h1><p>{data.period.start} a {data.period.end} · comparación con el período anterior</p></div><div className="summary-actions"><span className={`summary-status ${response.status}`}>{response.status === "live" ? "Snapshot disponible" : response.status === "partial" ? "Datos parciales" : "Unavailable"}</span><button className="summary-refresh" onClick={() => void update()} disabled={refreshing}><RefreshCw size={15} className={refreshing ? "spin" : ""} />{refreshing ? "Actualizando..." : "Actualizar datos"}</button></div></header>
    <div className="summary-meta"><span>Última actualización: <b>{date(updated)}</b></span><span>Fuente: <b>Snapshots persistidos · /api/summary</b></span>{response.error && <strong>{response.error}</strong>}</div>
    <div className="summary-kpis"><OverviewKpi icon={<ShieldCheck />} label="Health Score" value={data.overview.healthScore == null ? "No data" : `${data.overview.healthScore}/100`} tone="blue" /><OverviewKpi icon={<Search />} label="Keywords Top 10" value={number(data.overview.keywordsTop10)} tone="blue" /><OverviewKpi icon={<CheckCircle2 />} label="Acciones del mes" value={data.overview.monthlyActions == null ? "No data" : number(data.overview.monthlyActions)} tone="amber" /><OverviewKpi icon={<CircleAlert />} label="Issues" value={data.overview.issues ? number(data.overview.issues) : data.sources.audit === "unavailable" ? "No data" : "0"} tone="red" /></div>
    <SectionTitle icon={<BarChart3 />} title="Tráfico orgánico" detail="Últimos 30 días completos" />
    <div className="summary-metrics"><TrafficMetric label="Sesiones orgánicas" value={number(ga?.organicSessions)} current={ga?.organicSessions} previous={previous?.organicSessions} /><TrafficMetric label="Usuarios orgánicos" value={number(ga?.users)} current={ga?.users} previous={previous?.users} /><TrafficMetric label="Páginas vistas orgánicas" value="No data" note="GA4 no entrega esta métrica en el snapshot actual." /><TrafficMetric label="Tasa de interacción orgánica" value={percent(ga?.engagementRate)} current={ga?.engagementRate} previous={previous?.engagementRate} percentValue /></div>
    <SectionTitle icon={<Activity />} title="Tráfico desde IA" detail="Referrals reales detectados por GA4" />
    {ga?.aiSessions != null ? <div className="summary-metrics ai-metrics"><TrafficMetric label="Sesiones IA" value={number(ga.aiSessions)} current={ga.aiSessions} previous={null} /></div> : <Card><EmptyState title="No data available" detail="GA4 no tiene referrals de IA disponibles en este snapshot." /></Card>}
    <AuditBlock data={data} />
    <RankingsBlock data={data} />
  </div>;
}

function OverviewKpi({ icon, label, value, tone }: { icon: React.ReactNode; label: string; value: string; tone: string }) { return <div className={`summary-overview-kpi ${tone}`}><span className="summary-kpi-icon">{icon}</span><span>{label}</span><strong>{value}</strong></div>; }
function SectionTitle({ icon, title, detail }: { icon: React.ReactNode; title: string; detail: string }) { return <div className="summary-section-title"><span>{icon}</span><div><h2>{title}</h2><p>{detail}</p></div></div>; }
function TrafficMetric({ label, value, current, previous, note, percentValue }: { label: string; value: string; current?: number | null; previous?: number | null; note?: string; percentValue?: boolean }) { const delta = current != null && previous != null && previous !== 0 ? ((current - previous) / Math.abs(previous)) * 100 : null; const trend = delta == null ? "steady" : delta > 0 ? "up" : delta < 0 ? "down" : "steady"; return <div className="summary-traffic-card"><span className="traffic-icon"><BarChart3 size={17} /></span><span className="summary-metric-label">{label}</span><strong>{value}</strong>{note ? <small>{note}</small> : <small>vs. período anterior <b className={trend}>{delta == null ? "—" : `${delta > 0 ? "↑" : "↓"} ${Math.abs(delta).toFixed(1).replace(".", ",")}%`}</b></small>}{percentValue && !current && <small>No hay comparación disponible</small>}</div>; }
function AuditBlock({ data }: { data: Payload["data"] }) { const severity = (label: string) => data.audit.severity.find((item) => item.severity.toLowerCase() === label.toLowerCase())?.count ?? 0; const vitals = data.audit.vitals?.metrics ?? {}; return <><SectionTitle icon={<Gauge />} title="Auditoría Web" detail="Crawler, issues y Core Web Vitals desde el último snapshot" /><Card className="summary-audit"><div className="audit-top"><div><h3>Estado técnico</h3><div className="audit-score"><strong>{data.audit.score == null ? "No data" : data.audit.score}</strong><span>{data.audit.score == null ? "Sin auditoría disponible" : data.audit.score >= 80 ? "Bueno" : "Requiere atención"}</span></div></div><div className="audit-issues"><strong>{data.audit.issues ? number(data.audit.issues) : "No data"}</strong><span>Issues detectados</span><div className="severity-bars"><i><b style={{ width: `${data.audit.issues ? severity("Alta") / data.audit.issues * 100 : 0}%` }} /></i><i><b style={{ width: `${data.audit.issues ? severity("Media") / data.audit.issues * 100 : 0}%` }} /></i><i><b style={{ width: `${data.audit.issues ? severity("Baja") / data.audit.issues * 100 : 0}%` }} /></i></div><small>Alta {severity("Alta")} · Media {severity("Media")} · Baja {severity("Baja")}</small></div><div className="audit-vitals"><h3>Core Web Vitals</h3>{data.audit.vitals ? <><Vital label="LCP" value={vitals.lcp} unit="ms" /><Vital label="INP" value={vitals.inp} unit="ms" /><Vital label="CLS" value={vitals.cls} unit="" /></> : <span>No data available</span>}</div></div><div className="summary-card-footer"><span>Última auditoría: {date(data.audit.lastAudit)}</span><Link href="/auditoria-tecnica">Ver detalles <ArrowRight size={14} /></Link></div></Card></>; }
function Vital({ label, value, unit }: { label: string; value: number | null | undefined; unit: string }) { return <div><span>{label}</span><b>{value == null ? "No data" : `${label === "CLS" ? value.toFixed(3) : Math.round(value)}${unit}`}</b></div>; }
function RankingsBlock({ data }: { data: Payload["data"] }) { return <><SectionTitle icon={<Activity />} title="Rankings" detail="Consultas y posiciones de Search Console" /><Card className="summary-rankings"><div className="ranking-layout"><div className="ranking-counts"><RankCount label="Top 3" value={data.rankings.top3} tone="green" /><RankCount label="Top 10" value={data.rankings.top10} tone="blue" /><RankCount label="Top 30" value={data.rankings.top30} tone="amber" /><RankCount label="Sin posición" value={data.rankings.noPosition} tone="muted" /></div><div className="summary-table-wrap">{data.rankings.rows.length ? <table><thead><tr><th>Keyword</th><th>Pos.</th><th>Cambio</th><th>Impresiones</th></tr></thead><tbody>{data.rankings.rows.map((row) => <tr key={row.query}><th title={row.query}>{row.query}</th><td>{row.position == null ? "—" : row.position.toFixed(1)}</td><td>{row.previousPosition == null || row.position == null ? "—" : (row.previousPosition - row.position).toFixed(1)}</td><td>{number(row.impressions)}</td></tr>)}</tbody></table> : <EmptyState title="No data available" detail="No hay consultas persistidas de Search Console." />}</div></div><div className="summary-card-footer"><span>Fuente: GSC · historial diario</span><Link href="/keywords">Ver rankings <ArrowRight size={14} /></Link></div></Card></>; }
function RankCount({ label, value, tone }: { label: string; value: number; tone: string }) { return <div className={`rank-count ${tone}`}><span>{label}</span><strong>{number(value)}</strong></div>; }
